### ISSUE TITLE
Model Skins

### ISSUE THREAD

**Issue by xRJx** [CloudSixteen/Clockwork#110]
Having it so you can define model skins for items, classes and factions. For classes/factions, have it so you can either set a skin for a specific model or for all models assigned for that faction/class.

E.g.
CLASS.skin = 1;
FACTION.skin = 3;
ITEM.skin = 2;

FACTION.models  = 
{
 {"directory/blarg/test.mdl", 2},
 "derp/derp1/model.mdl"
};

etc.

iirc The items can already have skins set but they don't show up as the proper skin in your inventory, I could be wrong though. Clarification on that would be appreciated.

Edit:
Main reason for having it integrated is so that the model's skins would show up in character creation/selection.

**Comment by VortixDev** [comment]
Added to Trello.
