### ISSUE TITLE
HL2RP: Characters being deleted when re-entering server yet still in database.

### ISSUE THREAD

**Issue by CreepyYellowDuck** [CloudSixteen/Clockwork#129]
I've been having this error after this server I'm a part of had a small bug in its system. When the server reinstalled I had this bug where none of my created characters show.

If I create a new one and leave it disappears the next time I come on.
I also cannot remake the character because the server says the name is already in use. Which means the character must still exist somewhere in the database.

Only I'm having this bug at the moment. Everyone else is perfectly able to access their own characters from what I've seen and haven't lost any character, they also do not have them removed when they log back into the server.

**Comment by Ravagedyh** [comment]
Heya, this is happening to me also, was there a fix located? If not, this is a bump post.

I have a feeling that this is the cause - "[Clockwork] The 'PlayerDataStreamInfoSent' clockwork hook has failed to run." I don't know how to get rid of it/make it work.

**Comment by SomeSortOfDuck** [comment]
You need to post a full console log of the server, @Ravagedyh. Use pastebin.com or any other similar site.

**Comment by VortixDev** [comment]
In future, please use the forums for issues which you know do not happen to everyone.
