### ISSUE TITLE
The Clockwork Tool

### ISSUE THREAD

**Issue by kurozael** [CloudSixteen/Clockwork#151]
A GMod Tool for Clockwork.

Tools will be registered like this:

myTool = Clockwork.tool:New("Area Tool");
myTool.access = "a";

function myTool:OnDeploy() end;

function myTool:OnHolster() end;

Any hooks will be run so long as the player has the tool out.
You can use these for rendering, etc.

function myTool:OnLeftClick() end;

function myTool:OnRightClick() end;

function myTool:OnReload() end;

Tools will be able to do self:Call(data) to call a function with parameters on the client or the server.

Initial tools with release will include:

* Area Tool
* 3D Text Tool
* Door Commands Tool

**Comment by BrockDawg** [comment]
You should also add Static Prop Tool.

**Comment by skarphet** [comment]
@SomeSortOfDuck

**Comment by trurascalz** [comment]
Currently I have created a addon version without Clockwork Framework implementation, if your really desperate.

https://github.com/trurascalz/clockworkplugins/tree/master/Clockwork/clockworktoolguns Other than that, It is on my todo list at some point but not priority.

**Comment by SomeSortOfDuck** [comment]
I'll see what I can whip up @skarphet @trurascalz

**Comment by VortixDev** [comment]
Check recent GitLab commits.
