### ISSUE TITLE
[Request] Ambient Zone

### ISSUE THREAD

**Issue by Contamination** [CloudSixteen/Clockwork#153]
Ohai everyone, i'm working ona S.T.A.L.K.E.R. schema, and i've got some idea but it won't be cool without ambiances.
So, as a person without any code skill i'm requesting your help guyzzzzz.

I was thinking about something like Aera Display, something like a command using the sound browser:

/AmbientAdd (minimum point)
/Ambientadd (maximum point) then [What ambiance do you like to set? : sound/stalkerrp/ambient/example.wav]

Ambiant Area added.

**Comment by VortixDev** [comment]
This will be added to our to-do list. Thanks.
