### ISSUE TITLE
Storage panel issue

### ISSUE THREAD

**Issue by SuperItem** [CloudSixteen/Clockwork#170]
[ERROR] gamemodes/clockwork/framework/derma/cl_storage.lua:256: attempt to index local 'itemData' (a nil value)
1. Init - gamemodes/clockwork/framework/derma/cl_storage.lua:256
2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
3. RebuildPanel - gamemodes/clockwork/framework/derma/cl_storage.lua:199
4. Rebuild - gamemodes/clockwork/framework/derma/cl_storage.lua:223
5. unknown - gamemodes/clockwork/framework/derma/cl_storage.lua:432
6. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:151
7. unknown - lua/includes/modules/net.lua:32

This is the error that occurred after the UI update.
+ Salesman Panel error http://pastebin.com/RAC1mhwH

**Comment by Gr4Ss** [comment]
This has been fixed on the test branch, expect to see it on the master sometime soon.

Closing this already in the meantime.
