### ISSUE TITLE
MPF T-Posing

### ISSUE THREAD

**Issue by SkepticalTesticle** [CloudSixteen/Clockwork#175]
I just recently started up my server. We're getting things set up and one of the major setbacks is the fact that we can't get rid of the T-Posing for MPF models. The regular models, that is the default ones, are just fine, but the Metropolice Pack models just won't give in. We've installed the plugin that's supposed to fix it, and I'm certain in it's the right spot (garrysmod/gamemodes/cwhl2rp/plugins). Can anyone help us resolve this?

Thanks in advance.

**Comment by Gr4Ss** [comment]
Not familiar with the plugin (link would be nice), but are you certain the models are added onto the server? Easily tested by trying to spawn them as a ragdoll.

**Comment by SkepticalTesticle** [comment]
Plugin: https://www.dropbox.com/sh/xayqb62p99c77bn/AABnrHCHRPOs4yTczS-nHNM7a?dl=

Yes, I just ran a test to spawn some of the ragdolls (and the playermodel versions) and both spawned without issues. The T-Posing persists, however.

**Comment by Gr4Ss** [comment]
That link doesn't work btw.

**Comment by SkepticalTesticle** [comment]
Oh, Para must have deleted it from his dropbox. I'll see if I can find another version of it somewhere.

**Comment by SkepticalTesticle** [comment]
Okay, I managed to fix it without the use of a plugin.

I have this thread to thank: http://forums.cloudsixteen.com/index.php?topic=2647.0

**Comment by Gr4Ss** [comment]
Alright, good to hear. Busy coding things so didn't really search the forums. But it's fixed so closing this.
