### ISSUE TITLE
Broken config.

### ISSUE THREAD

**Issue by Zeeeeeeeeeeebra** [CloudSixteen/Clockwork#178]
![broken config](https://cloud.githubusercontent.com/assets/10453058/5666994/1c6ba684-975c-11e4-8873-0274fd964113.jpg)

Some options do not show the option to change them, only the description text, as show above.

**Comment by xRJx** [comment]
I can confirm that this happened/happens to other people.

**Comment by Gr4Ss** [comment]
Seen it happen as well, usually clicking the bottom blue bar twice (once to hide the config option, once to show it) will fix it iirc.

**Comment by xSpArkYx** [comment]
Not trueeee! It usually makes it worse for me.

This needs a fix, now!

**Comment by CuddlyAngel** [comment]
It appears to be only checkboxes that are affected by this bug, I worked around this by making my checkboxes into number sliders from 0 to 1. Check the checkbox code, it might be where the bug is for this.

**Comment by Gr4Ss** [comment]
[img]http://i.imgur.com/ACrf1d8.png[img]
Can't seem to reproduce this on the test branch, so going to assume this isn't happening anymore, meaning it'll be fixed on the master once I merge test into it (which is soon'ish). Going to leave this open for a bit just in case though.

**Comment by Gr4Ss** [comment]
@xSpArkYx @xRJx @Zeeeeeeeeeeebra Can you confirm if this still happens on the current github version?

**Comment by CuddlyAngel** [comment]
It's been fine for me so far, and I had the problem.

**Comment by sly775** [comment]
I have the problem sometimes too, the easiest way to get around this is to use /cfgsetvar (your variable) (true/false) so like /cfgsetvar recognise_system true

**Comment by CuddlyAngel** [comment]
This has been fixed in the upcoming 0.93 version of CW.
