### ISSUE TITLE
Fist keys glitch

### ISSUE THREAD

**Issue by JampoJP** [CloudSixteen/Clockwork#179]
My friend has set up a Clockwork hl2 rp server. We have encountered a glitch where when you slect the keys item it brings up the black gloved fists. If you change your weapon back to hands they won't go away untill you rejoin the server. If you join the server and don't bring up the keys but instead raise your fists the black hands don't appear like they should.

Note: The server has NO plugins installed and is a completely fresh copy of CW:HL2RP. Also this was after the key regeneration (May not be linked but though i'd say anyway).

All help is appreciated.

**Comment by Gr4Ss** [comment]
@JampJP I can't seem to reproduce this.
