### ISSUE TITLE
Your own ESP info appears twice

### ISSUE THREAD

**Issue by Gr4Ss** [CloudSixteen/Clockwork#180]
![image](http://i.imgur.com/fmUWLpU.png)

@CuddlyAngel 

Just go into observer and look up to see your own name (with admin ESP on, of course).

**Comment by CuddlyAngel** [comment]
This is strange, because sometimes it does it and sometimes it doesn't, and only with the extra ESPs. I'll look into this.

**Comment by CuddlyAngel** [comment]
I believe I've solved this.
