### ISSUE TITLE
Broken hands.

### ISSUE THREAD

**Issue by rida220** [CloudSixteen/Clockwork#181]
On my friends HL2RP server i selected my hands tool but the fists are raised on screen but when i click it doesnt punch so when i hold R the fists are still there and i can punch but when i move my mouse the screen slightly shakes everytime i move my mouse so it's hard to aim this also happens with guns how do i fix this problem?

**Comment by Ptilly** [comment]
Im currently having the same issue with this aswell. The fists do not do damage, and only push.

**Comment by ZigBomb** [comment]
Disable Free-Aiming in the configuration of the server.

**Comment by VortixDev** [comment]
I haven't been able to reproduce this.
