### ISSUE TITLE
Classes/Factions not Showing in Scoreboard

### ISSUE THREAD

**Issue by TheSmallChild** [CloudSixteen/Clockwork#187]
When I/other people make a character, their class/faction name says "Unassigned" or "Joining/Connecting". I've made classes for each faction and added this hook right here:

function Schema:GetPlayerScoreboardClass(player)
	local customClass = player:GetSharedVar("customClass");
	local faction = player:GetFaction();

	if (faction == FACTION_ASSAULT) then
		return "555th Grand Imperial Assault Battallion";
	elseif (faction == FACTION_SPECOPS) then
		return "242nd Grand Imperial Special Operations Battallion";
	end;
	elseif (faction == FACTION_MEDICAL) then
		return "Imperial Medical Division";
	end;
	elseif (faction == FACTION_HEAVY) then
		return "363rd Grand Imperial Heavy Ordnance Division";
	end;
	elseif (faction == FACTION_RECRUIT) then
		return "345th Grand Imperial Recruit Battallion";
	end;
	elseif (faction == FACTION_SITH) then
		return "Sith Council Mother-Fuckers";
	end;
	elseif (faction == FACTION_ENGINEER) then
		return "172th Imperial Field Engineer Division";
	end;
	elseif (faction == FACTION_PROBE) then
		return "Imperial Reconnaissance Probe";
	end;
end;

**Comment by SomeSortOfDuck** [comment]
Because you're not using if statements correctly. Not only that, but you don't even need to do anything with this hook, so I'm not sure why you're using it.

**Comment by SomeSortOfDuck** [comment]
I don't even think there's an appropriate label for this, but it's not Clockwork's fault, it's yours. You're not doing things correctly.

**Comment by Gr4Ss** [comment]
This is indeed a problem on your end.
