### ISSUE TITLE
[HL2RP] Combine locks parents to wrong entities on load

### ISSUE THREAD

**Issue by Atebite** [CloudSixteen/Clockwork#188]
See sv_schema.lua, line 354.

When combine locks are loaded, they may be parented to a non-door entity (e.g. if ents.FindInSphere finds a map entity first). This breaks the lock's functionality on the door and it'll appear somewhere that likely isn't on the door.

Can be fixed with a simple entity class whitelist for the results of ents.FindInSphere.

**Comment by SomeSortOfDuck** [comment]
We'll work on a fix for this. Thanks Ate.

**Comment by skarphet** [comment]
RJ, can you take a look at this?

**Comment by xRJx** [comment]
I can. Atebite if you're still here, can you tell me the map/location where this occurred so I can recreate it?

**Comment by Atebite** [comment]
Somewhere on rp_industrial17_v1. Just look at the code and you should understand the issue.

ents.FindInSphere finds the worldspawn or some other entity before it finds the door and parents to that instead.

**Comment by xRJx** [comment]
Ye, I recall seeing that in the loading function before.

Thanks, I'll work on it ASAP.

**Comment by VortixDev** [comment]
Thanks Atebite, this has been fixed now.
