### ISSUE TITLE
(HL2RP) "SetGlobalVar"

### ISSUE THREAD

**Issue by Applad** [CloudSixteen/Clockwork#189]
Hello,

today Garry's Mod got an update. I updated my gameserver aswell. Then I started it and the server doesn't appear to work anymore. Users are still able to join, but they'll receive a "dead-screen" like in Sandbox, but can't respawn. Here's a log of my gameserver console, it's getting spammed with it.
*[Clockwork] The 'Tick' hook failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:3921: attempt to call upvalue 'SetGlobalVar' (a nil value)*
Users on the server itself are getting spammed with this message in their console.
*[Clockwork] The 'CalcView' hook failed to run.
gamemodes/clockwork/framework/cl_kernel.lua:851: attempt to index field 'Client' (a nil value)*

And yes, I am using plugins. Before the update, my gameserver was running fine without issues.

**Comment by CuddlyAngel** [comment]
This is a problem with certain functions being removed from GMod that Clockwork relies on. Shared Variables need to be reworked, we're aware of this. Just hold tight.

**Comment by SomeSortOfDuck** [comment]
Oh shit, I wasn't expecting it to be today. I'll have a fix out when I get home unless another dev whips one up.

**Comment by Applad** [comment]
"https://gitlab.com/Clockwork/clockwork/commit/65d8a8dcd7388e379e9526de61053e4892188278 Fixed on github, going to work on a fix for the store version now." - Gr4Ss on the forums, closing this now.
