### ISSUE TITLE
Broken scoreboard, error upon opening menu with TAB

### ISSUE THREAD

**Issue by unusualcrow** [CloudSixteen/Clockwork#193]
http://i.imgur.com/H8xe0EK.png
Multiple people were on the server. Not moving the scoreboard down as it should.
http://i.imgur.com/0EDU8mi.png
When opening the tab menu.
http://i.imgur.com/8ewAcyJ.png
Selection color stays there after running the mouse over an option.
http://i.imgur.com/dmF7LQu.jpg
I equipped and held a suitcase.

**Comment by VortixDev** [comment]
Please ask for help regarding your own server's issues on the forums (http://forums.cloudsixteen.com)
