### ISSUE TITLE
Invisible Items

### ISSUE THREAD

**Issue by fayzgolden666** [CloudSixteen/Clockwork#194]
Never experienced this before.

http://cloud-4.steamusercontent.com/ugc/707401792821395401/1F7945F69217E5DFFF777DB4B7974803E33ECCA4/

All items are invisible, no idea why.

**Comment by fayzgolden666** [comment]
Nobody?

**Comment by skarphet** [comment]
Any plugins to take note of? Clean installation?

**Comment by VortixDev** [comment]
Cannot reproduce. Please keep all issues only you are having to the forums (http://forums.cloudsixteen.com)
