### ISSUE TITLE
Broken Character Names/Descriptions

### ISSUE THREAD

**Issue by PaladinReese** [CloudSixteen/Clockwork#195]
Ever since the Garry's Mod update and then the Clockwork update soon to follow, there has been some issues with our server. Our server host updated to meet the demand of Garry's Mod, so the server, gamemode, and schema all run.

Here are some of the problems:

1) Some people get stuck in the clockwork initializing screen.
2) When someone is fully connected on a character, other people see only their Steam username in IC, LOOC, and OOC chat.
3) Some players see other players with only their default descriptions set up by the gamemode itself.
3A) Metrocops are suppose to be recognized by everyone by default, this does not occur with the characters mentioned in "3". It says "A metrocop wearing a uniform and a radio" and "you do not recognize this person." and does not show up on the scoreboard as if the person isn't there. When these people speak...their steam username comes up.
3B) if you know the characters name and do ulx/administrator commands on the person, it still affects them.

**Comment by kurozael** [comment]
Hi PaladinReese,

In your SRCDS console, after connecting to CloudAuthX, it should say "Your Clockwork version is: X" what does it say?

If it doesn't say this, you aren't connected to CloudAuthX and therefore won't receive the over-the-air patch.

**Comment by PaladinReese** [comment]
This is what it says: L 03/13/2015 - 17:36:12: Lua Error: [CloudAuthX] Your Clockwork version is currently: 0.925

**Comment by PaladinReese** [comment]
Additionally, I got these as well upon further inspection:

[CloudAuthX] Checking and downloading default plugins...
[CloudAuthX] delaylooc plugin is up to date.
[CloudAuthX] storeflag plugin is up to date.
[CloudAuthX] trackstats plugin is up to date.
[CloudAuthX] reportplayer plugin is up to date.

**Comment by CuddlyAngel** [comment]
Those are just over-the-air update checks for default plugins, don't worry about that.

**Comment by BrockDawg** [comment]
I am getting this exact same issue and I am not sure why.

**Comment by Heldex** [comment]
Same issue.

**Comment by VortixDev** [comment]
Cannot replicate. Please keep issues which others do not have to the forums (http://forums.cloudsixteen.com)
