### ISSUE TITLE
Loading in problems.

### ISSUE THREAD

**Issue by HazmatRanger** [CloudSixteen/Clockwork#196]
When people load into my server, they are having this pop up in front of everything. http://imgur.com/VPDpARy They can't type, can't access the tab menu, or f1. 

When people are in chat, it uses their steam name instead of their Character's name.
http://imgur.com/NuwMoXl

**Comment by VortixDev** [comment]
I cannot replicate this. Please use the forums to request help for issues only you are having (http://forums.cloudsixteen.com)
