### ISSUE TITLE
Data: [Clockwork] The 'staticESPSync' datastream has failed to run. gamemodes/clockwork/gamemode/external/pon.lua:361: attempt to call a nil value

### ISSUE THREAD

**Issue by BoboHobo** [CloudSixteen/Clockwork#197]
Hello, recently we've been having this error with our server, and when we proceed to leave spawn area, it will lag the server to hell and no one is able to move. Whenever we open the Clockwork Tab Menu, the Yellow Colors stay even when you are not hovering over the selection, and we have no idea what the problem could be. Any ideas?

**Comment by CuddlyAngel** [comment]
Hi, sorry for the way too late reply. Are you still having this issue?
