### ISSUE TITLE
cl_theme Issues.

### ISSUE THREAD

**Issue by ZigBomb** [CloudSixteen/Clockwork#198]
Main Menu/Tab Text Colors refuse to be changed, even if there is input in the cl_theme file changing the color codes for them.

http://steamcommunity.com/sharedfiles/filedetails/?id=412414251

**Comment by skarphet** [comment]
@SomeSortOfDuck believe this is known?

**Comment by SomeSortOfDuck** [comment]
It is known and will be fixed in the next update of GMod guaranteed or sooner.

**Comment by CuddlyAngel** [comment]
I believe this has been fixed, please open another issue if this has persisted through the last GMOD update.
