### ISSUE TITLE
Phase Four Gamemode not loading

### ISSUE THREAD

**Issue by ElToblahoe** [CloudSixteen/Clockwork#199]
Hey guys. I am the owner of a phasefour server which has been bought from this website a few days ago. Our server provider told us to download this file http://pastebin.com/U3CdVCK8 because garry's recent update was making our server crash 24/7 but now the gamemode is completely broken. some clients clockwork won't even initialize. After loading a character the tab menu is broken and the gamemode does not work propperly at all? But we need this lua file to fix our server/client crashes. Thanks.

**Comment by SomeSortOfDuck** [comment]
Remove the file and wait for a real fix from Facepunch.
