### ISSUE TITLE
Losing Characters

### ISSUE THREAD

**Issue by Badsh0t** [CloudSixteen/Clockwork#200]
So whenever I join specifically the Dynex server (they might have some plugins that are doing this) I go ahead and make my character, disconnect, and rejoin the server (i have to cancel and rejoin a couple times due to the initializing glitch) the character is no longer. And when I try to remake a character with the same name it tells me it's taken

**Comment by SomeSortOfDuck** [comment]
This is not a place to submit bug reports for specific servers. If that server is the only one this happens on, then there's nothing we can do.
