### ISSUE TITLE
bg_gradient

### ISSUE THREAD

**Issue by Zigalishous** [CloudSixteen/Clockwork#201]
bg_gradient doesn't load for some servers, loads for others.
You get gray instead of the new blue and red.

**Comment by CuddlyAngel** [comment]
Sorry for the incredibly late reply, are you still having this issue?

**Comment by ZigBomb** [comment]
I'll have to check, as of now I have custom gradients on that don't work, I'll get back to you soon about it. I don't have high hopes that it will though.

**Comment by CuddlyAngel** [comment]
Alrighty, sorry again about the late reply.

**Comment by ZigBomb** [comment]
It's completely fine, one moment.

**Comment by CuddlyAngel** [comment]
Try the new release and see if that fixes things for you.

**Comment by ZigBomb** [comment]
Where exactly is it?

**Comment by ZigBomb** [comment]
Inb4 Right here on Github, When I try to unzip the zip in my root dir, it doesn't extract correctly at all.

**Comment by CuddlyAngel** [comment]
I've got no idea how to help you with your linux unzipping :c

**Comment by ZigBomb** [comment]
Guess I'll wait for CAX!

**Comment by skarphet** [comment]
What happened when you tried to extract?

**Comment by ZigBomb** [comment]
There wasn't an error, it simply didn't extract to any folders at all, just made it's own DIR in my server root.

**Comment by skarphet** [comment]
What command did you use?

**Comment by ZigBomb** [comment]
The command you use to extract zip files in Linux...
unzip..

**Comment by skarphet** [comment]
http://hastebin.com/ibifutitaw.avrasm

Tested on my Mac as well as Ubuntu 14.04, 14.10 and 15.04. Tested on latest CentOS, too. Seems to be working as intended for me?

**Comment by skarphet** [comment]
I could try to pack it up as a .tar if you'd like?

**Comment by ZigBomb** [comment]
That's not the problem, it extracts fine, it simply doesn't go to the proper directories.
![fuck](https://cloud.githubusercontent.com/assets/9789933/8331118/7b95c902-1a54-11e5-959c-5b3e77e16686.png)

You can see here that I have a dir called server files, where the gameserver is located. I start at the root of that and you can see that it simply it makes it's own directory rather than extracting them. I posted a picture of whats in the dir it makes, and it's all the files.

**Comment by VortixDev** [comment]
That's because you don't simply extract it and be done - Once you extract it, take the content of the Clockwork directory and upload it to serverfiles.

**Comment by ZigBomb** [comment]
So now it doesn't work like it always used to?

**Comment by skarphet** [comment]
Only the store version is extract and go. Github has never been like that.

**Comment by skarphet** [comment]
Try https://storage.googleapis.com/clockwork/misc/Clockwork-github.zip

**Comment by ZigBomb** [comment]
Received wrong spawn count 24 when at 23

Oh boy.

**Comment by skarphet** [comment]
Well then... @kurozael

**Comment by skarphet** [comment]
For the record ZigBomb, sorry I couldn't be of much help. Once we get to the point where its a CAX error it's pretty much out of our control.. :(

**Comment by Zigalishous** [comment]
It's fine, I'm used to things not working unfortunately.

**Comment by skarphet** [comment]
Sorry to hear you say that.. Hopefully the issue should be sorted soon, but I ain't gonna promise anything :(

**Comment by Zigalishous** [comment]
Of course not, it's just how things are. Everything doesn't work magically and that's understandable for a fully custom framework and some DRM.

**Comment by skarphet** [comment]
I will @Zigalishous
