### ISSUE TITLE
Crash to desktop upon joining Clockwork server.

### ISSUE THREAD

**Issue by Tazmily** [CloudSixteen/Clockwork#203]
Hello, a friend of mine has a Clockwork server set up, and it's currently closed for set-up and development. Whenever I attempt to join, however, I crash instantaneously upon getting to the "Please wait while Clockwork initializes" screen. There is no error message or anything that might suggest that anything has gone wrong. The game simply crashes. In the past 3 days I have managed to successfully connect to the server maybe three times. I have uninstalled and re-installed my addons, updated my drivers, and restarted Steam, and server-side my friend has tried everything he could, be it clearing my user data from the SQL, removing and adding addons, and restarting the server. None of these have worked.

I've attached the most recent MDMP file to the post to see if you guys can gather anything from that.

Thank you for the assistance in advance.

http://puu.sh/hFi56/fd74d9fb75.mdmp

**Comment by SomeSortOfDuck** [comment]
It's something wrong with your computer.
