### ISSUE TITLE
Nametag Problem

### ISSUE THREAD

**Issue by DivineGamingOW** [CloudSixteen/Clockwork#205]
Its been really annoying that everyone can see each other's names even when a admin is in OB or no-clip people can see their names. I been trying everything to remove this problem but nothing works. This can be used as meta and im trying to prevent that. Image below:
![image](https://cloud.githubusercontent.com/assets/12385666/7556505/0cc74bda-f728-11e4-9975-8e34ed336f8e.png)

**Comment by SomeSortOfDuck** [comment]
I don't understand.

**Comment by VortixDev** [comment]
A player's name shows above his head to those who recognise him, otherwise the physical description will show. MPF names show without having to be recognised initially.
