### ISSUE TITLE
"Examine" issue.

### ISSUE THREAD

**Issue by Applad** [CloudSixteen/Clockwork#207]
Hello.

I have noticed that the "Examine" button (which pops up when you press E on an item) does not have any effect. From what I have seen, it should write the description of the item into the chatbox, but this process does not seem to work on my server. Is this known or are there any fixes for this issue around?

Best regards.

**Comment by CuddlyAngel** [comment]
This is a known issue, but it's not high priority. We'll try to get it fixed asap. :)

**Comment by CuddlyAngel** [comment]
This has been fixed and will be released with version 0.93.
