### ISSUE TITLE
Combine sound when running

### ISSUE THREAD

**Issue by TheGayJunes** [CloudSixteen/Clockwork#208]
Hello,

Citizen make the combine sound when they walk or run. Is a way to fix it ??

thanks

**Comment by D66Ha** [comment]
You have edited the class of the citizens?
Do you have any plugins installed?

**Comment by VortixDev** [comment]
Hello,
I haven't been able to reproduce this bug. You may ask for help with your own server's issues on the forums. http://forums.cloudsixteen.com
