### ISSUE TITLE
Stamina Plugin

### ISSUE THREAD

**Issue by redcatjack** [CloudSixteen/Clockwork#211]
It appears the Config Options are not working for the Stamina Plugin, They are not in the 'System > Config' Menu and if you try and set it via '/CfgSetVar stam_drain_scale 20' it says 'stam_drain_scale is not a valid config key!' This is the same with the other Stamina Config Options

**Comment by CuddlyAngel** [comment]
Is the stamina plugin unloaded? Can you send a pastebin of your console during start up, please?

**Comment by redcatjack** [comment]
It would appear something has caused it to disable automaticly on server restart, Which is strange as it was enabled prior to this new version. Oh well it's working now. Closed
