### ISSUE TITLE
SRCDS.exe Crashing with Clockwork 0.93

### ISSUE THREAD

**Issue by redcatjack** [CloudSixteen/Clockwork#212]
So everything was fine upuntill I installed the new version of CW.
Here is the console.log and the crash mdmp
(Removed Links because it contained IP adress ect)

**Comment by CuddlyAngel** [comment]
Thread 0 (crashed)
 0  gmsv_cloudauthx_win32.dll + 0x1bf23
    eip = 0x5a19bf23   esp = 0x0077c768   ebp = 0x0077c778   ebx = 0x00000000
    esi = 0x008520c8   edi = 0x0077c8d4   eax = 0x1e3fc224   ecx = 0x1c82e059
    edx = 0x00090000   efl = 0x00010206

It looks like CAX crashed your server. Nothing we as the developer team can do, since kuro won't let anyone access it. Try to keep restarting it until it loads, that's all I can tell ya'. :'/

**Comment by redcatjack** [comment]
Damn, Thanks awayway. Time to wait for Kuro to look atit.

**Comment by redcatjack** [comment]
UPDATE:
It appears switching back to 0.92 has fixed it.

**Comment by skarphet** [comment]
What schema were you using?

**Comment by redcatjack** [comment]
Half-Life 2 Roleplay

**Comment by skarphet** [comment]
Okay, I'll poke Conna about this on here and our dev chat
@kurozael

**Comment by skarphet** [comment]
Per what we spoke about on the forums - mind posting your report here once you've tested?

**Comment by redcatjack** [comment]
Will done once i've tested

**Comment by redcatjack** [comment]
UPDATE:
After testing, everything seems to be fine now. What ever Kuro did to CAX seems to have fixed this.
I'll leave this open so you see it. if you want you may close it after you have seen it.
If it happens again I will Re-Open this.

**Comment by skarphet** [comment]
Thanks!
