### ISSUE TITLE
Optimization issues

### ISSUE THREAD

**Issue by Chessnut** [CloudSixteen/Clockwork#213]
I've noticed with the recent release, some of the optimizations will actually hinder performance.

For instance, in some of the hooks the arguments become a local variable. (https://github.com/CloudSixteen/Clockwork/blob/428d65c1d09b6ae4d3e3179fdc078c1da54dcffe/Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua#L482)

This is actually slower than just using the arguments directly.

Also some of the local version of functions are found in the function rather than outside where it should be.(https://github.com/CloudSixteen/Clockwork/blob/428d65c1d09b6ae4d3e3179fdc078c1da54dcffe/Clockwork/garrysmod/gamemodes/clockwork/framework/sh_kernel.lua#L515)

**Comment by skarphet** [comment]
Thanks for pointing those out Chess, much appreciated. Feel free to point out any other stuff you see - I'll get one of the devs to look at it

**Comment by CuddlyAngel** [comment]
I've fixed this in the private repo, will continue testing there before pushing a possibly broken change. This'll be in the next patch.

**Comment by Chessnut** [comment]
Also you can try removing some of the syntactic sugar in expensive
hooks/functions to improve performance.
