### ISSUE TITLE
Weapon Error

### ISSUE THREAD

**Issue by user2g** [CloudSixteen/Clockwork#214]
[Clockwork:Kernel]
The 'GetPlayerESPInfo' clockwork hook has failed to run.
gamemodes/clockwork/framework/cl_kernel.lua:2283: attempt to call method 'GetPrintName' (a nil value)

Only happens when observer listing off the weapon in their hand.

**Comment by skarphet** [comment]
What do you mean by your last sentence?

**Comment by CuddlyAngel** [comment]
It's a weird bug with the ESP that I can't seem to pinpoint, trying to figure it out.

**Comment by CuddlyAngel** [comment]
Go into your cl_kernel and try replacing Clockwork:GetPlayerESPInfo with this

-- Called when extra player info is needed.
function Clockwork:GetPlayerESPInfo(player, text)
	if (player:IsValid()) then
		local weapon = player:GetActiveWeapon();
		local health = player:Health();
		local armor = player:Armor();
		local colorWhite = Color(255, 255, 255, 255);
		local colorRed = Color(255, 0, 0, 255);
		local colorHealth = colorWhite;
		local colorArmor = colorWhite;
		
		table.insert(text, {player:SteamName(), Color(170, 170, 170, 255), nil, nil, self.player:GetChatIcon(player)})

		if (player:Alive() and health > 0) then

			if (CW_CONVAR_ESPBARS:GetInt() == 0) then
				colorHealth = self:GetValueColor(health);
				colorArmor = self:GetValueColor(armor);
			end;

			table.insert(text, {"Health: ["..health.."]", colorHealth, {health, player:GetMaxHealth()}})
			
			if (player:Armor() > 0) then
				table.insert(text, {"Armor: ["..armor.."]", colorArmor, {armor, player:GetMaxArmor()}, Color(30, 65, 175, 255)});
			end;
		
			if (weapon and IsValid(weapon)) then			
				local raised = self.player:GetWeaponRaised(player);
				local color = colorWhite;

				if (raised == true) then
					color = colorRed;
				end;
				
				if (weapon.GetPrintName) then
					local printName = weapon:GetPrintName();

					if (printName) then
						table.insert(text, {printName, color})
					end;
				end;
			end;
		end;
	end;
end;

**Comment by user2g** [comment]
Working.
