### ISSUE TITLE
Static Props not saving

### ISSUE THREAD

**Issue by PrimarchLionheart** [CloudSixteen/Clockwork#216]
Upon a server restart on .93 the static props no longer load, however already staticed entities have been saved.

**Comment by skarphet** [comment]
@VortixDev

**Comment by CuddlyAngel** [comment]
https://youtu.be/gs8Cw0hCoUw I'm not able to reproduce this bug. :/

**Comment by PrimarchLionheart** [comment]
In .93 isn't /staticpropadd removed? And replaced with /staticadd?

**Comment by CuddlyAngel** [comment]
It is removed, but I used it to prove that static props carry over from 0.92 to 0.93. Isn't that what your problem is?

**Comment by PrimarchLionheart** [comment]
What happens is they carry over, and then randomly upon some restarts with no script errors the file for the props just wipes and becomes nothing, just the props file.

**Comment by CuddlyAngel** [comment]
Do you mean the props file in the static ents folder, or the staticprops file from the statcprops plugin?

**Comment by PrimarchLionheart** [comment]
I mean in settings under the plugins folder theres a folder called props and then a file with our map name that is currently 60 something kb, then randomly we'll restart and the file is still there but is 0kb.

**Comment by CuddlyAngel** [comment]
It's supposed to do that, so that when it carries over the props from the old staticprops plugin, it doesn't produce doubles when the staticprop is the same as the staticent that was carried over before.

**Comment by PrimarchLionheart** [comment]
It doesn't carry them over...

**Comment by YKhan98** [comment]
Static props with this version DO NOT save on my server at all. I tried any valid prop that I know would save normally, did /staticadd, and after waiting for the data save interval (if that even matters), I look in the FTP and I do not see a "props" or "rp_industrial17_v1" folder. Upon restart, the props disappear. I tried this with the toolgun and with the command "/staticadd".

**Comment by YKhan98** [comment]
@VortixDev @CuddlyAngel @xRJx Please fix this!

**Comment by CuddlyAngel** [comment]
https://github.com/CloudSixteen/Clockwork/issues/233
