### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by Chessnut** [CloudSixteen/Clockwork#217]
I've noticed that Clockwork always seemed to have documentation that does not really help explain the code at all.

Example:

```
--[[
    @codebase Shared
    @details A function to encode a URL.
    @param String The URL to encode.
    @returns String The encoded URL.
--]]
function Clockwork.kernel:URLEncode(url)
```

The function name obviously explains that it encodes the URL, but one may be confused by what that means exactly. 

Another example:

```
-- A function to convert a string to a color.
function Clockwork.kernel:StringToColor(text)
```

That's great that it can convert a string to a color, but the comment is still useless since the function name explains that it does so. However, what should the string look like? How does it work? Etc...

Comments like these are riddled throughout the framework and does not really serve its purpose of documenting the framework well. This becomes an issue of quantity over quality.

**Comment by xRJx** [comment]
I'm pretty most if not all initial documentation was done by kurozael. As I go through adding documentation so a parsing program will work on it I'll see about changing things to give a better explanation.

**Comment by Chessnut** [comment]
The 0.93 commits still contain pretty bad comments. If you are going to add
documentation it should be actually useful otherwise it might as well not
be there.

**Comment by xRJx** [comment]
Yeppers.
