### ISSUE TITLE
Various Errors on 0.93

### ISSUE THREAD

**Issue by micafire** [CloudSixteen/Clockwork#218]
# Server Side
Instance one: Clockwork loads peacefully, but giving these few errors below.
![Image One](http://i.imgur.com/Ri3loX4.png)
![Image Two](http://i.imgur.com/jWNX1zB.png)
![Image Three](http://i.imgur.com/QU9C873.png)

# Client-Side:
Instance One: I see a "Loading..." text fade and nothing else happens.
[Clockwork] The 'RenderScreenspaceEffects' hook failed to run.
gamemodes/clockwork/framework/cl_kernel.lua:2791: attempt to index local 'systemTable' (a nil value)

Awaiting feedback and support to help continue debugging the version.

**Comment by micafire** [comment]
This seems to happen when you have custom-plugins made by third-party, I will teest each plugin and get back to the plugin that is causing the issues.

**Comment by micafire** [comment]
I have found he culprit, it is "Character customization" by Duck. Another error has came along clicking "Business" Menu....
![Error](http://i.imgur.com/t2vNELy.png)

**Comment by user2g** [comment]
@SomeSortOfDuck

**Comment by PrimarchLionheart** [comment]
Getting a similar error too.


[ERROR] gamemodes/clockwork/gamemode/external/utf8.lua:1977: Invalid UTF-8 character
  1. error - [C]:-1
   2. utf8charbytes - gamemodes/clockwork/gamemode/external/utf8.lua:1977
    3. utf8sub - gamemodes/clockwork/gamemode/external/utf8.lua:2067
     4. GetTextSize - gamemodes/clockwork/framework/sh_kernel.lua:1497
      5. WrappedText - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:682
       6. Add - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:984
        7. Decode - gamemodes/cwhl2rp/plugins/vortiguantlanguage/plugin/cl_plugin.lua:264
         8. unknown - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:1075
          9. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:168
           10. unknown - lua/includes/extensions/net.lua:32


I'm not sure what triggers it
The vortiguant language plugin is a red herring, this occurred when no vorts were even online.

**Comment by CuddlyAngel** [comment]
This could simply be a problem with an outdated plugin(s).

**Comment by micafire** [comment]
is there a way we could find the plugin that does it? Like making clockwork yelp the error and issue and prevent execution of the outdated plugin? Also I'm trying to make a list of fixes and such. Additional help is greatly appreciated.

**Comment by CuddlyAngel** [comment]
I can't think of anything to help further debug errors short of editing the base of GMOD itself. Thanks for all the bug finding you're doing. :D
