### ISSUE TITLE
Conflicting licenses in datastreams

### ISSUE THREAD

**Issue by mooshbeef** [CloudSixteen/Clockwork#219]
There are two confliciting licences in the [datastream library](https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_datastream.lua). This is one I happened to come across, there may be more.

**Comment by CuddlyAngel** [comment]
Fixed.

https://github.com/CloudSixteen/Clockwork/commit/5b520488f183132c05f866341eed510dbae3b4e2
