### ISSUE TITLE
HL2RP- Loading in with Grey Screen over face *Please Help*

### ISSUE THREAD

**Issue by Ethanio** [CloudSixteen/Clockwork#220]
Just spent a good deal of my sleeping time setting up this painstaking HL2RP server. Finally, everything is rigged and good. I load right in as soon as I can and almost dance when I see that it works! I create the character, but the transparent, grey loading-in overlay is over my vision and it wont go away. I cannot pull out any tools (toolgun, fists, etc.) but I can go into observer and move and whatnot. Is is a  common bug for a brand-fresh server?

**Comment by Ethanio** [comment]
I also cannot speak or use the speech menu. Like, the hell?

**Comment by VortixDev** [comment]
Hi Ethanio,
Please try updating your GMod server with SteamCMD and see if it works afterwards.
