### ISSUE TITLE
[P4] Not being able to make an alliance

### ISSUE THREAD

**Issue by Doodleh** [CloudSixteen/Clockwork#221]
[ERROR] 158: attempt to index global 'tmysql' (a nil value)
1. unknown - [string "--! CAX 4..."]:158
2. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:89
3. unknown - lua/includes/extensions/net.lua:32

The mySQL is properly setup as the character information does save as it should.

**Comment by CuddlyAngel** [comment]
Does this still occur with the P4 update?
