### ISSUE TITLE
Client crash. on client joining this happens on random occasions

### ISSUE THREAD

**Issue by user2g** [CloudSixteen/Clockwork#223]
2841(1228.102476):  GetLuaTable != TABLE! Type is: 02840(1228.102375):  
[ERROR] lua/includes/util.lua:171: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:171
   2. unknown - gamemodes/clockwork/framework/cl_kernel.lua:62

2839(1228.102292):  
[ERROR] lua/includes/util.lua:171: attempt to index local 'object' (a number value)
  1. IsValid - lua/includes/util.lua:171
   2. unknown - gamemodes/clockwork/framework/cl_kernel.lua:62

**Comment by Zigalishous** [comment]
2841(1228.102476): GetLuaTable != TABLE! Type is: 02840(1228.102375):

TABLES.
