### ISSUE TITLE
Urgent fix needed.

### ISSUE THREAD

**Issue by user2g** [CloudSixteen/Clockwork#224]
[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

[Clockwork:Surface Texts]
The 'PostDrawTranslucentRenderables' hook has failed to run.
lua/includes/modules/markup.lua:245: attempt to index upvalue 'utf8' (a nil value)

Gmod update

**Comment by CuddlyAngel** [comment]
Solved.
