### ISSUE TITLE
UTF-8 Error

### ISSUE THREAD

**Issue by kkj4818** [CloudSixteen/Clockwork#225]
TAB Menu Doesn't open

![default](https://cloud.githubusercontent.com/assets/5549849/9815861/3c1f5338-58d4-11e5-947f-43e26ca77a25.PNG)

**Comment by CuddlyAngel** [comment]
Figuring this out already, the GMOD update broke it. Sorry for the wait.

**Comment by CuddlyAngel** [comment]
Please download the plugin here and place it in your schema's plugins http://forums.cloudsixteen.com/threads/hotfix-fix-for-broken-cw-from-sept-11-2015-gmod-update.16346/#post-167917 Tell me if this solved your problem so I can close the issue, or provide further support if it didn't.

**Comment by kkj4818** [comment]
It doesn't work. Even server crashes.

![problem](https://cloud.githubusercontent.com/assets/5549849/9829777/8536b0a0-594e-11e5-958e-2f9a2d16a179.PNG)

**Comment by CuddlyAngel** [comment]
Try a fresh install of everything (schema, CW, srcds), maybe it didn't update correctly. This seems like there's a problem with the srcds, as it errors out at a bunch of globals before the plugin is even loaded.

**Comment by kkj4818** [comment]
The problem have solved! Thank you!

**Comment by CuddlyAngel** [comment]
Happy to help! <3
