### ISSUE TITLE
Hl2rp items disapearing

### ISSUE THREAD

**Issue by Spectregaming** [CloudSixteen/Clockwork#227]
I just set up my server, everything works fine except dropped items simply disapear

**Comment by kodafine** [comment]
This is a known bug with Linux, usually when the player that has the error occur to them reconnects, it's fixed.

Dunno if there is a real fix, but if there is, @VortixDev would know.

**Comment by CuddlyAngel** [comment]
Is this still occurring for you? Can you post a pastebin of your console.log from start up to when a dropped item disappears if so?

**Comment by MKOChiclees** [comment]
Ehm... hello guys. This problem happens to me too,and when i reconnect that works . I want to know if there is a solution for the problem

**Comment by xRJx** [comment]
I'll be marking this Issue as Solved. A user (murray-elijah) pointed out a lot of Issues that are solved or expired, so I'm working on that to tidy up Clockwork's Issues.
