### ISSUE TITLE
Game crashes when I finish a quiz for a Clock Work server

### ISSUE THREAD

**Issue by SovietPotato** [CloudSixteen/Clockwork#228]
On a server my friend made, there's a quiz that you have to do. The first time I try it, the game crashes when I click continue. I verify game cache, let the files download, then I try again. After the second time, I crash again. The third time, I got them all wrong on purpose then I crash. Anything I can do to get it to work?

**Comment by satoshiaaron** [comment]
Things I would recommened right of the bat is to disable all workshop addons you don't need for the server and then try. If not that then try a full reinstallation.

**Comment by SovietPotato** [comment]
I tried that but my game crashed again.

**Comment by satoshiaaron** [comment]
What system are you running on? My frie d had the exact same problem on Mac.

**Comment by SovietPotato** [comment]
I use Windows 7 on a desktop PC.

**Comment by satoshiaaron** [comment]
How much ram is usable on your PC
