### ISSUE TITLE
Buisness not spawning

### ISSUE THREAD

**Issue by Kingodkk** [CloudSixteen/Clockwork#229]
When i buy something from the buisness menu it takes the tokens but does not spawn the box with 5 of the items?

**Comment by satoshiaaron** [comment]
Sometimes the items themselves are still skeleten and have no functions. Send the item code?

**Comment by Kingodkk** [comment]
Its all hl2rp relatet items. All guns food etc everything when i drop it it's gone

**Comment by CuddlyAngel** [comment]
Did you put all the models from the Clockwork and HL2RP folders into your server models?

**Comment by Kingodkk** [comment]
Yes i did

**Comment by satoshiaaron** [comment]
Check all your business and spawning related variables

**Comment by CuddlyAngel** [comment]
Does this still occur after recent updates to Clockwork?
