### ISSUE TITLE
Static props are permanent

### ISSUE THREAD

**Issue by ghost** [CloudSixteen/Clockwork#233]
Static props are permanent. They do not delete with the /staticremove command OR if you delete the prop.

There is no way to delete/remove a static prop at all.

**Comment by 2142k** [comment]
FYI:
Latest Stock Github CW with Stock HL2RP Schema.

No extra addons/files at all.

**Comment by xRJx** [comment]
I'll be marking this Issue as Solved. A user (murray-elijah) pointed out a lot of Issues that are solved or expired, so I'm working on that to tidy up Clockwork's Issues.
