### ISSUE TITLE
Clockwork Introduction is permanently stuck.

### ISSUE THREAD

**Issue by 2142k** [CloudSixteen/Clockwork#234]
Clockwork Introduction plays EVERY time, even after disabling it and restarting, even after creating a new character.

It's permanently stuck on.

Clean install, github clockwork, clean hl2rp stock store install. No added files at all.

**Comment by CuddlyAngel** [comment]
CloudAuthX runs code that does it, you'd have to overwrite the datastream hook for it with a plugin. I think duck's P4 plugin does this, I think he posted it somewhere on the forums.

**Comment by 2142k** [comment]
Negative on that. 

Confirmed clean install of github CW (current)  and HL2RP. Still happens.

I cannot be the only one with this issue.

**Comment by 2142k** [comment]
Please mark as resolved. Is a non-issue.
