### ISSUE TITLE
HL2RP - System config edits - Cannot change some values

### ISSUE THREAD

**Issue by cannibalis** [CloudSixteen/Clockwork#235]
Some values in the config area in-game cannot be changed even by the owner of the schema. 

https://i.gyazo.com/4fbfe16eea046ce1304842edb5862a88.png

**Comment by CuddlyAngel** [comment]
Upgrade to the latest version of CW on the Github here, go to releases, then 0.94.1

**Comment by 2142k** [comment]
I'm unable to replicate this with latest github and stock/store hl2rp on my server.

http://puu.sh/l3NHJ/b83e1a0dd2.jpg

Works fine.
