### ISSUE TITLE
Clockwork UI Suggestion

### ISSUE THREAD

**Issue by kodafine** [CloudSixteen/Clockwork#238]
###### "Just a suggestion, at some point I'd like to see the Clockwork scoreboard UI overhauled. It's getting a bit old now and it doesn't render player profiles or (sometimes) playermodels correctly. I've been working a bit on it but can't really get anywhere with it."

I also think an overhaul of the UI altogether would be really sweet. I know it was just tweaked recently, but I think a new derma texture for the Inventory and Settings menu and such would make it look way nicer and sleeker.

**Comment by CuddlyAngel** [comment]
Yes, an overhaul of the UI is on the list of things todo. Thank you for the suggestion. ^~^

**Comment by SpencerSharkey** [comment]
May I recommend looking into using the Webkit control for parts of the menu system?

The menu state as it is suffers from extreme inheritance. It's gotten to a point where it's definitely a bit bloaty.
