### ISSUE TITLE
Grenade Glitch

### ISSUE THREAD

**Issue by ParaShock** [CloudSixteen/Clockwork#239]
Hiya. On the HL2RP schema (and possibly others), there's a glitch where people can equip a grenade, throw it, and change chars back and forth to regain the grenade. I took a look at the script, and it basically the grenade stays in your equipment tab after throwing it.

I suggest forcing the player to holster the grenade after they throw it. (Holstering a thrown grenade will negate it's access to inventory.)
For example, code something where it forces the command to holster when a player's grenade munition hits 0.

**Comment by CuddlyAngel** [comment]
This has been added to the list of bugs to fix, thank you for bringing this to our attention.
