### ISSUE TITLE
Cider Two Joining Error

### ISSUE THREAD

**Issue by r0wi3** [CloudSixteen/Clockwork#241]
Fresh install & upon first join.

Rowie|2|STEAM_0:0:95887804] Lua Error:

[ERROR] RunString:591: attempt to call method 'GetMaterial' (a nil value)
1. INTRO_CALLBACK - RunString:591
2. unknown - RunString:650

[Rowie|2|STEAM_0:0:95887804] Lua Error:
[Clockwork] The 'PostDrawBackgroundBlurs' plugin hook has failed to run.
RunString:536: attempt to index local 'material' (a nil value)

[Rowie|2|STEAM_0:0:95887804] Lua Error:
[Clockwork] The 'PostDrawBackgroundBlurs' plugin hook has failed to run.
RunString:536: attempt to index local 'material' (a nil value)

[Rowie|2|STEAM_0:0:95887804] Lua Error:
[Clockwork] The 'PostDrawBackgroundBlurs' plugin hook has failed to run.
RunString:536: attempt to index local 'material' (a nil value)

[Rowie|2|STEAM_0:0:95887804] Lua Error:
[Clockwork] The 'PostDrawBackgroundBlurs' plugin hook has failed to run.
RunString:536: attempt to index local 'material' (a nil value)

Known?

**Comment by satoshiaaron** [comment]
Sorry for the late reply. This issue is fixed now. We also started adding new materials. Can now be closed.
