### ISSUE TITLE
HL2RP Black Screen Issue

### ISSUE THREAD

**Issue by SapphireRed** [CloudSixteen/Clockwork#242]
I've been running an HL2RP server for about a month and a half now, and only after updating to Clockwork 0.94.51 did this issue happen. Basically, the citizens can move around freely and see fine when spawning in, but after a charswap they see nothing but the screen they had before the charswap (with the exception of the tab menu and the character selection screen; in other words, they see their character's view before the charswap).

With the MPF, they see only a black screen upon spawning, with their HUD working fine. Looking in the console, this error is repeated over and over again:

[Clockwork] The 'PostDrawTranslucentRenderables' hook failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:2532: attempt to index local 'color' (a nil value)

This error and other similar to it appear in a constant stream. Any known fixes?

**Comment by CuddlyAngel** [comment]
Does this still occur when updating to the latest version (0.94.72)?

**Comment by Aforgomon** [comment]
Yes, the issue persists. I've updated the server with every new version of Clockwork that has been released, but to no avail. I can't seem to find anything on the Cloud 16 forums or Steam forums about this specific bug either, and the fixes for bugs that resembled this even a little bit did nothing.

**Comment by CuddlyAngel** [comment]
Have you tried this without any third party plugins/addons installed? Those could be the culprit.

**Comment by Aforgomon** [comment]
I will try disabling the plugins I've uploaded from the Plugin Center and removing the plugins I've downloaded from elsewhere, as well as removing the content pack that I have set up on Steam.

By the time I read your message 0.94.74 was already out, so I have that installed.

**Comment by Aforgomon** [comment]
I've removed all addons and plugins, but the issue persists.

**Comment by CuddlyAngel** [comment]
What version were you running before you upgraded? Do you remember?

**Comment by Aforgomon** [comment]
Yes, I was running the version of Clockwork available on the Cloud 16 store. I believe it's 0.925.

**Comment by CuddlyAngel** [comment]
https://github.com/CloudSixteen/Clockwork/releases/tag/v0.94.17

Try using that one, if it works, I'll have to pinpoint a possible error with a desync in branches.

**Comment by Aforgomon** [comment]
After installing the version you provided, the issue persists.

My co-owner pointed out a console error that he is receiving that he believes may be associated to the issue.

[Clockwork:Weapon Select]
The 'HUDPaintImportant' hook has failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:2532: attempt to index local 'color' (a nil value)

[Clockwork:Kernel]
The 'HUDPaintForeground' clockwork hook has failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:2496: 'cwMainText14' isn't a valid font


[Clockwork:Weapon Select]
The 'HUDPaintImportant' hook has failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:2532: attempt to index local 'color' (a nil value)
[Clockwork] The 'HUDDrawScoreBoard' hook failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:3480: attempt to index local 'colorInfo' (a nil value)
[Clockwork] The 'HUDPaint' hook failed to run.
gamemodes/sandbox/gamemode/cl_init.lua:72: attempt to call method 'PaintWorldTips' (a nil value)

**Comment by CuddlyAngel** [comment]
Can you try putting -condebug in your command line and pasting your console.log into a pastebin and posting it here? Be sure to remove any private info like passwords or IPs.

**Comment by Aforgomon** [comment]
Do you mean the command line for the server or for my client? If you mean the server, the server host doesn't allow me to make fully customized command lines. I can edit a few variables such as web console, Rcon passwords, map, etc. but I can't add segments such as what you provided.

**Comment by CuddlyAngel** [comment]
Try looking in your ftp for a console.log file, or ask your provider about it.

**Comment by Aforgomon** [comment]
I have a database of logs, yes, but none that give detailed information errors one could see in the console. Just the variables that are defined in the server.cfg.

**Comment by Aforgomon** [comment]
When I look in my console while playing as an MPF I get a constant stream of these two errors: gamemodes/clockwork/framework/sh_kernel.lua:2539: attempt to index local 'color' (a nil value)
[Clockwork] The 'PostDrawTranslucentRenderables' hook failed to run.

**Comment by CuddlyAngel** [comment]
Please open a ticket on the store support site, and provide info for a temp sub user that has access to the rcon, restarts/stops, and ftp please so I can tinker and make it work.

**Comment by CuddlyAngel** [comment]
https://github.com/CloudSixteen/Clockwork/releases/tag/v0.96.2
Please try this release and see if it solves this issue.
