### ISSUE TITLE
Plugin menu bug.

### ISSUE THREAD

**Issue by Lv6** [CloudSixteen/Clockwork#247]
On attempting to open the plugin menu with 9.5, this error is put into the console:

[ERROR] gamemodes/clockwork/framework/system/sh_manage_plugins.lua:39: bad argument #1 to 'pairs' (table expected, got nil)
  1. pairs - [C]:-1
   2. OnDisplay - gamemodes/clockwork/framework/system/sh_manage_plugins.lua:39
    3. Rebuild - gamemodes/clockwork/framework/derma/cl_system.lua:62
     4. DoClick - gamemodes/clockwork/framework/derma/cl_system.lua:93
      5. unknown - gamemodes/clockwork/framework/derma/cl_infotext.lua:138

and nothing is returned.

**Comment by TheGarry** [comment]
Replace Clockwork.plugin.stored in sh_manage_plugins.lua (line 39) with Clockwork.plugin:GetStored()

**Comment by CuddlyAngel** [comment]
This should be fixed in this commit.
https://github.com/CloudSixteen/Clockwork/commit/343274d15afc8a6d14e543f9ccffdf0f91e4f7ff
