### ISSUE TITLE
HL2RP character customization ERROR for LUA 

### ISSUE THREAD

**Issue by UberSerpent** [CloudSixteen/Clockwork#248]
[ERROR] gamemodes/cwhl2rp/schema/derma/cl_character.lua:762: attempt to index field 'startButton' (a nil value)
  1. Init - gamemodes/cwhl2rp/schema/derma/cl_character.lua:762
   2. Create - lua/includes/extensions/client/panel/scriptedpanels.lua:153
    3. RefreshPanelList - gamemodes/clockwork/framework/libraries/cl_character.lua:281
     4. Callback - gamemodes/cwhl2rp/schema/derma/cl_character.lua:122
      5. Callback - gamemodes/cwhl2rp/schema/derma/cl_character.lua:329
       6. Func - gamemodes/cwhl2rp/schema/derma/cl_frame.lua:27
        7. Run - lua/derma/derma_animation.lua:31
         8. AThink - gamemodes/cwhl2rp/schema/derma/cl_frame.lua:81
          9. unknown - gamemodes/cwhl2rp/schema/derma/cl_frame.lua:86

**Comment by CuddlyAngel** [comment]
It seems like you tried to make an edit to the HL2 RP schema. This isn't recommended because errors like this can pop up. Try reinstalling fresh unedited copies of Clockwork and HL2 RP onto your server.
