### ISSUE TITLE
Config keeps restarting.

### ISSUE THREAD

**Issue by DivineGaming** [CloudSixteen/Clockwork#250]
![](https://i.gyazo.com/3948a462d7bb07c38c67b36396bb3e49.png)
Every time I restart my server my config keeps restarting. This started happening when I added a new class. If anyone knows what source this starts from or anyone who has had this before, please any help I would be grateful for.

**Comment by VortixDev** [comment]
I recommend trying with a fresh install of the latest Clockwork release if you're experiencing this.
