### ISSUE TITLE
We keep on getting band and insulted by admin

### ISSUE THREAD

**Issue by Ijustwantfun** [CloudSixteen/Clockwork#251]
Me and a friend try and join a clock works server its all good we get in i put my real name . I start walking around and some guy come up to me and starts insulting my name and asks how old i am and he laughs at me. Then out of no where my friend gets band for trolling and then so do I. A week passes and my friend joins back he instantly gets banned for "Minge, we had to deal with you in the past" about a hour later I join (not knowing my friend joined a hour earlier) and they change my name out of no where then I get banned for "You're a minge too, we had to deal with your u and your friend in the past" which is complete crap.

My stream name is Mazda_Poop

**Comment by Zigalishous** [comment]
This is for direct framework issues and or commits. This github is not meant for community sever related issues. Please seek the forum site of the community you were on or it's owner, as this github is simply for the framework and we do not control community servers.
