### ISSUE TITLE
Backsword 2 has no holdtypes?

### ISSUE THREAD

**Issue by SISNEVS** [CloudSixteen/Clockwork#253]
PICTURES: http://imgur.com/a/XfUgZ
it looks like there's no holdtypes im not sure if the logs are affiliated with it.
DataTable warning: (class point_spotlight): Out-of-range value (-8.164717) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (3.381778) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-14.828206) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-4.705763) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-7.333901) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-14.723042) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-2.724674) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-8.657495) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-7.823325) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (9.909599) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-0.653629) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-11.869066) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-13.826575) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-10.875778) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (2.432383) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-10.471048) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (1.158841) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-8.128997) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (7.164390) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (6.790429) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (8.962396) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-4.178515) in SendPropFloat 'm_flSpread', clamping.
Giving TESTCHAR a bs_cs_sg552
DataTable warning: (class point_spotlight): Out-of-range value (-3.724294) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-6.432748) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (9.631688) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (15.309899) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (10.239725) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-7.461123) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (1.937859) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: point_spotlight: Out-of-range value (12.396721) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-7.528283) in SendPropFloat 'm_flSpread', clamping.
DataTable warning: (class point_spotlight): Out-of-range value (-6.554955) in SendPropFloat 'm_flSpread', clamping

PICTURES: http://imgur.com/a/XfUgZ

**Comment by Zigalishous** [comment]
Hey, thanks for information!
I don't really know what's going on with the hold types of the base at the moment, but I'll try my best to figure it out, I'll give you a link to a minor patch when I find the issue, use it until the next public version of Clockwork.

It doesn't seem like those logs are affiliated with the base itself.

**Comment by SISNEVS** [comment]
May I have the link to the minor patch then, thanks?

**Comment by Zigalishous** [comment]
Alright, here's what I've established.
There's nothing wrong with the base on my end. I am using the latest public build, nothing seems to be wrong. However, I'd like for you to check if there's a regular backsword folder in your Clockwork plugins, not Backsword 2, but backsword. If it's there, delete it and tell me what happens.

**Comment by Zigalishous** [comment]
I'm now aware and established with this issue.
I'm going to be fixing it in the next version of BackSword 2.
Thanks.
