### ISSUE TITLE
[Phase Four] prop damage

### ISSUE THREAD

**Issue by Quenser6011** [CloudSixteen/Clockwork#254]
The problem of how to remove the purple color when prop takes damage?
How to remove damage?
[Prop](http://forums.cloudsixteen.com/proxy.php?image=http%3A%2F%2Fforums.cloudsixteen.com%2Fproxy.php%3Fimage%3Dhttp%253A%252F%252Fi.imgur.com%252FAUMMVfU.jpg%26hash%3D3d1d439ab2998e373c9cedb46b95d971&hash=846cf6b503a09f90c2a4593498e522ea)

**Comment by xRJx** [comment]
That's like trying to remove crafting or mining from vanilla Minecraft.

**Comment by Quenser6011** [comment]
Russian players like all break. Props no exception

**Comment by SelmarK** [comment]
It was in sv_hooks but now... there External... thx

**Comment by xRJx** [comment]
I'll be marking this Issue as Solved. A user (murray-elijah) pointed out a lot of Issues that are solved or expired, so I'm working on that to tidy up Clockwork's Issues.
