### ISSUE TITLE
[Clockwork:Kernel] The 'Tick' hook failed to run.

### ISSUE THREAD

**Issue by cornpop37** [CloudSixteen/Clockwork#255]
My server was working perfectly, all today, the second I restart it to get a new map. Boom, error floods my console and it appeared once during the setup.

The full error is as follows
`[Clockwork:Kernel]
The 'Tick' hook failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:1214: attempt to perform arithmetic on a nil value`

**Comment by Kefta** [comment]
It seems your Clockwork version differs from the one on the GitHub

**Comment by CuddlyAngel** [comment]
Please try updating to the latest release and see if the issue continues for you.
https://github.com/CloudSixteen/Clockwork/releases/tag/v0.96.2
