### ISSUE TITLE
Serial Key FORMAT!

### ISSUE THREAD

**Issue by Alpha321** [CloudSixteen/Clockwork#256]
We had a clockworks server, we just today had it wiped because of stupid addons that got on the server, we couldnt trace, etc. After this we reinstalled CW, we have the serial key, but I found a "serial.cw" and not a "serial.cfg". So I deleted the "serial.cw" and make a new file, named "serial.cfg" its in the same location, and I made that, it was blank, so I just put the key in, is there a format to put the config file in, with words inside the file, or do I just put a serial key, if I just put a serial key in, I tried that and it loads as sandbox!

**Comment by trurascalz** [comment]
Open a ticket in the store. This  is not an issue for github.

**Comment by Alpha321** [comment]
Store, where is that, link at least?

**Comment by trurascalz** [comment]
Store.cloudsixteen.com
