### ISSUE TITLE
Clockwork HL2RP Model Glitch Help Request

### ISSUE THREAD

**Issue by Alpha321** [CloudSixteen/Clockwork#257]
Hello, I run a clockwork hl2rp server, I am having a problem, the problem is weird...we have barely any items in our content pack over workshop, we have added plugins and we are curious to know if anybody knows what plugin or anything is causing this. The server when you join should download basic stuff, our server adds models, some we did not add. Some of the models are:
"models/player/sniper.dx80.vtx.ztmp"
"models/player/soldier_animations.mdl"
"models/player/spy.dx80.vtx"
"models/player/spy.mdl"
THIS NOT EVEN 1/32. ALL THE MODELS DURING THE JOINING END WITH ".ztmp"
PLEASE HELP!

**Comment by Zigalishous** [comment]
Maybe someone is adding content to your workshop collection you are adding content to without you knowing. I don't believe this a is a Clockwork issue, therefore it shouldn't be on the github. You're responsible for your server's own content, not us.

**Comment by Zigalishous** [comment]
resolved

**Comment by Alpha321** [comment]
Not resolved.

**Comment by Alpha321** [comment]
Another can possibly help, just leave it open for another, please.

**Comment by Zigalishous** [comment]
We don't include models such as spy in our Clockwork content or our HL2RP content.

**Comment by Zigalishous** [comment]
The only way I can think of this being relevant is if you have a plugin that is adding models, which if that's the case we'd still need more than model lists.

**Comment by Zigalishous** [comment]
close #257
