### ISSUE TITLE
Entity Menus

### ISSUE THREAD

**Issue by SpencerSharkey** [CloudSixteen/Clockwork#258]
Please remove my Entity Menus from the commercially distributed Clockwork. Nobody came out to ask me for permission for re-use here...

**Comment by trurascalz** [comment]
Can you please contact Conna at connawiles@gmail.com

**Comment by kurozael** [comment]
Hi @SpencerSharkey, I recall us having a conversation about you being fine with us incoporating your Entity Menus (with credit) into Clockwork in the past and as such it has only just come up as an option, hence our implementing of them. Please e-mail me for further discussion :)
