### ISSUE TITLE
Bug with 0.96.1 and items

### ISSUE THREAD

**Issue by redcatjack** [CloudSixteen/Clockwork#263]
_"Item entities will now remove if they are out of the map, or if the item they represent isn't loaded on the server."_

Seems to remove ALL items dropped, I tested with HL2RP, and even the defualt items just vanish when dropped

**Comment by satoshiaaron** [comment]
There were a few bugs that weren't patched or were picked up after the release. Most of them are already fixed for the next update. Anna is working hard to fix them now. Will be patched very soon.

**Comment by CuddlyAngel** [comment]
Yeah, like in the next hour or so. Thank you for bringing this to my attention.

**Comment by CuddlyAngel** [comment]
Please try using this release and see if it fixes your issue.

https://github.com/CloudSixteen/Clockwork/releases/tag/v0.96.2

**Comment by redcatjack** [comment]
This is now been fixed, Thanks NightAngel
