### ISSUE TITLE
Users cannot use /ARequest, only operators.

### ISSUE THREAD

**Issue by zapk** [CloudSixteen/Clockwork#264]
The command looks like it should be for users to request help from staff, but only operators/admins can use it.

I'm not sure if it's supposed to be like that, but it seems a little odd to me.

**Comment by TylerGeorges** [comment]
Yes, this was my fault. Will be fixed in the next update.

**Comment by TylerGeorges** [comment]
Yes, this is my fault. Will be fixed in the next update.

**Comment by xRJx** [comment]
I'll be marking this Issue as Solved. A user (murray-elijah) pointed out a lot of Issues that are solved or expired, so I'm working on that to tidy up Clockwork's Issues.
