### ISSUE TITLE
Server Issue: Need to find character storage files.

### ISSUE THREAD

**Issue by TheIrishTemplar-TCP** [CloudSixteen/Clockwork#267]
I have an error with updating my server, steam was being a 'bully' and it was not correctly updating my server.. I fixed all that the hard way, but now I want to bring my player and character data and put it back into my servers files.. I have a backup saved from the old server that has the characters and players ON it... Where are the character-player storage files at in the server directory?

**Comment by trurascalz** [comment]
The Character data is stored either on a MYSQL server if you added any MYSQL information to your clockwork.cfg or if you left it blank it would be in sv.db
