### ISSUE TITLE
Another Admin Problem

### ISSUE THREAD

**Issue by Jokuu** [CloudSixteen/Clockwork#272]
Hey! :)
So, we tried that what CuddyAngle told us yesterday and it didnt worked very well, the console says my owner rank is "protected", i think ULX destroyed so many things because the admin system is totally broken.
We tried to remove the owner rank, give me SA and give me Owner again, but after that i had the owner rank with the key icon but without any admin rights.
Thank you for help. :)
(We would do a totally server clear if nothing else helps.)

**Comment by CuddlyAngel** [comment]
Try going manually into your SQL database with HeidiSQL if it's remote, or an SQLite reader if you're using SQLite, then manually changing the usergroup in the players table to superadmin.

If that fails, a server wipe might be advised.

**Comment by Jokuu** [comment]
It failed, he can give me the rights but after a mapchange/server restart they are gone.
The permissions seem to update, though the server doesn't appears to read them or something.

**Comment by CuddlyAngel** [comment]
Server wipe then, you're not supposed to use ULX with CW for this among a few other reasons.

**Comment by Jokuu** [comment]
What do i have to wipe from the database? Everything?

**Comment by CuddlyAngel** [comment]
Actually, what addons and plugins do you have running that could alter admin permissions? It might be one of those wrecking havoc.

**Comment by Jokuu** [comment]
**Plugins:** PluginID: 89 Name: Apply;  PluginID: 128 Name: Civil Workers' Union Faction; PluginID: 130 Name: View Model Hands Fix; PluginID: 81 Name: Backpacks, PluginID: 121 Name: ItemSpawner v2, PluginID: 173 Name: Combine Sniper Item, PluginID: 140 Name: Combine typing Sounds, PluginID: 60 Name: Affective Wounds, PluginID: 75 Name: Player Flags, PluginID: 175 Name: Customizable Metropolice Animation Fix, PluginID: 171 Name: Combine Voices, PluginID: 178 Name: PlayerCanQuickRaise Config Setting, PluginID: 138 Name: DispatchVoices, PluginID: 79 Name: Checkpoint, PluginID: 148 Name: MetroPolice v5 Model Pack - Animations Fix, PluginID: 181 Name: Better Viewdata, PluginID: 109 Name: Perma Remove

**Comment by Jokuu** [comment]
Checkpoint maybe?

**Comment by CuddlyAngel** [comment]
try removing it

**Comment by Jokuu** [comment]
Didnt changed everything, i think the wipe is the best choice now
