### ISSUE TITLE
Connect failed: Can't connect to MySQL server on '127.0.0.1' (111) 

### ISSUE THREAD

**Issue by Sours999** [CloudSixteen/Clockwork#273]
Message:
Connect failed: Can't connect to MySQL server on '127.0.0.1' (111) 

Comes when I go on the Plugin Manager.

http://i.imgur.com/7xNBGYs.png?1

**Comment by trurascalz** [comment]
This issue is known and under investigation.

(this also does not belong here as the website clearly states, use the store)
