### ISSUE TITLE
FPS Issue?

### ISSUE THREAD

**Issue by Mhatt12** [CloudSixteen/Clockwork#279]
So, i've been playing HL2RP since OpenAura, and suddenly my fps on any Clockwork server drops. When in game, I get 25fps flat, and when i open console it raises to 100+, and it doesnt do that on sandbox, or Nutscript. I've already reinstalled all my addons, and my friend told me it might have something to do with the overlay. Anybody got a fix, or maybe a possible fix?

**Comment by mynameisshi** [comment]
What map does this occur on?

**Comment by Mhatt12** [comment]
rp_city17_build210

**Comment by Heldex** [comment]
Maybe you have too much props, I'd suggest doing a prop wipe and check if it improves it and also don't stack like 50 props in the plaza once, be carefull on how you place props just dont make them all in one place.

**Comment by Mhatt12** [comment]
It's not the props, we just changed the map and we have no props, and it still lags like hell. But as I said before, if it was the props it would change my overall fps, not just a vsync on the standard cover of the screen. Whenever I open console it raises from 120, and it removes the overlay. Could it be the overlay?

**Comment by ruben-16** [comment]
Might be the overall massive amount of Derma that is prepared and presented on screen, all of that derma vanishes when you hit escape.

**Comment by Mhatt12** [comment]
And there's nothing to fix that?
