### ISSUE TITLE
Help setting up API key in HL2RP

### ISSUE THREAD

**Issue by Ethanio** [CloudSixteen/Clockwork#282]
Hi, two questions. One, I have my workshop collection, how do I hook the API key up to my server running off of NFOServers? Also, when setting the map rotation, will simply having the map in the collection work? Thanks!

**Comment by ruben-16** [comment]
This isn't a question for the Clockwork github, as it isn't Clockwork related. Put in a support ticket and or how to edit your server.cfg to link your server to your collection. This isn't the place for it.
