### ISSUE TITLE
Wont start

### ISSUE THREAD

**Issue by gmanc2** [CloudSixteen/Clockwork#287]
<details> 
  <summary>Q1: Console Logs </summary>
   A1: rcon from "192.95.1.186:49966": command "kickall Server is shutting down" Adding Path: [/home/content/cstrike/] FIND [/home/content/cstrike//*.vpk] ADDING [/home/content/cstrike//cstrike_pak_000.vpk] Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar Game_srv.so loaded for "Garry's Mod" Initializing Steam libraries for secure Internet server Logging into anonymous gameserver account. Fetching Workshop Addons.. No -authkey Changing gamemode to HL2 RP (cwhl2rp) Unknown command "cl_cmdrate" Unknown command "cl_updaterate" Unknown command "rate" Network: IP 192.95.1.187, mode MP, dedicated Yes, ports 27015 SV / 27005 CL PREP OK [Clockwork] Framework is initializing... Please wait while Clockwork initializes...  [ERROR] gamemodes/clockwork/gamemode/init.lua:36: Couldn't load module library! 1. require - [C]:-1 2. unknown - gamemodes/clockwork/gamemode/init.lua:36 3. DeriveGamemode - [C]:-1 4. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6  Couldn't Load Init Script: 'clockwork/gamemode/init.lua' [AddCSLuaFile] Couldn't find 'weapons/addon.txt/shared.lua' (<nowhere>) [AddCSLuaFile] Couldn't find 'weapons/garrysmod.dat/shared.lua' (<nowhere>) [AddCSLuaFile] Couldn't find 'effects/addon.txt/init.lua' (<nowhere>) [AddCSLuaFile] Couldn't find 'effects/base/init.lua' (<nowhere>) [AddCSLuaFile] Couldn't find 'effects/dof_node/init.lua' (<nowhere>) [AddCSLuaFile] Couldn't find 'effects/garrysmod.dat/init.lua' (<nowhere>) Making workshop gamemode available for client download ConVarRef room_type doesn't point to an existing ConVar Executing dedicated server config file server.cfg Using map cycle file 'cfg/mapcycle_default.txt'. ('cfg/mapcycle.txt' was not found.) KeyValues Error: LoadFromBuffer: missing { in file scripts/propdata/addon.txt  Nav File is wrong or something (4) Initializing Steam libraries for secure Internet server Logging into anonymous gameserver account. Server logging enabled. Server logging data to file logs/L0607002.log L 06/07/2016 - 21:40:15: Log file started (file "logs/L0607002.log") (game "/home/gmcgame/williamr/332/garrysmod") (version "6021") Unknown command "sbox_allownpcs" Unknown command "sbox_plpldamage" Unknown command "sbox_playergod" Unknown command "sbox_maxspawners" Unknown command "sbox_maxturrets" Connection to Steam servers successful.
</details>

Any idea as to whats causing it?

**Comment by CuddlyAngel** [comment]
'Couldn't load module library!'

You didn't install either the lua/bin .dll files or the libmysql.dll file properly.

**Comment by gmanc2** [comment]
They are installed correctly I've tried this 3 times on three different computers! I simply drag them into their respective folders.
