### ISSUE TITLE
Serial key disabled?

### ISSUE THREAD

**Issue by Spoderman12** [CloudSixteen/Clockwork#288]
Hello,

Today I tried to make my Clockwork: Half-Life 2 Roleplay and as I understand it says that my key was disabled.
[CloudAuthX] Initializing secure connection to CloudAuthX.
[CloudAuthX] You are not authorized by CloudAuthX to use HL2 RP!
06/09/2016 03:32:05: Lua Error [CloudAuthX] Loading encrypted Clockwork externals, please wait...
[CloudAuthX] Loading encrypted Clockwork externals, please wait...
[CloudAuthX] Cannot load external code without authentication!
Maybe it comes with the thing that someone stole mine by saying that he could help me to "translate" this schema..
Im the laxou55 forum customer I dont know if you can find me by my forum name.
If you could give me a new one or reactivate it or anything else it could be awesome thanks for help.

**Comment by MrMe0w** [comment]
Try going to cwhl2rp folder, deleting any files that have "serial" in their name. Then create a "serial.cfg" file and paste your clockwork key that you got from the store there. Check that there are no spaces in that file at all. Then try launching your server again.

**Comment by Spoderman12** [comment]
I tried what you said and my gamemode is Unauthorised

Addons have changes - remounting
Network: IP 192.168.1.90, mode MP, dedicated No, ports 27015 SV / 27005 CL
Connecting to 87.98.188.6:27040...
LAN servers are restricted to local clients (class C).

Ignoring blacklisted server: AeroServers Star Wars RP[NEW]Commanders NeededlStaff Needed @ 185.38.151.231:27105

If you want we can speak on steam so I could give you my ftp to see what's the problem
http://steamcommunity.com/profiles/76561198258911281/

**Comment by Spoderman12** [comment]
Im pretty sure he stole my serial key and used it for himself it could explain why I cant use mine for myself.

**Comment by MrMe0w** [comment]
Even if he stole your key that wouldn't be the cause of auth problems. Check the following:
Is your gamemode folder name 'cwhl2rp'?
Are you setting the gamemode correctly via +gamemode 'cwhl2rp'?
Have you ever modified (edited) any files within Clockwork framework or HL2RP schema?

As a last resort - try doing a complete reinstall. It can be that you're missing some key files required for Clockwork to run properly. Also, triple-check your serial key.

**Comment by Spoderman12** [comment]
My folder name is cwhl2rp and I cant put cwhl2rp +gamemode cwhl2rp because im hosted and I edited nothing

**Comment by Spoderman12** [comment]
As you can see I tried on 2 different hosts and same problem
http://image.noelshack.com/fichiers/2016/23/1465495186-20160609195755-1.jpg
I think my key is disabled or something wrong with it

**Comment by Spoderman12** [comment]
In README I found that

You have been given a new serial key! If you want to keep your old one,
you can write a support ticket containing the following information:
	1. Your old serial key.
	2. The schema the serial key is for.
And we will change your new one back to your old one for you.

Sorry about this, it won't happen again, we promise.

a49fd06ee01cc052999465fa092fbf64 my old one

**Comment by Spoderman12** [comment]
Yes some guys already got this problem and it's because my key is invalid so could you please send me a new fresh one on my email ? dim.du.54@live.fr

**Comment by ruben-16** [comment]
Are you using a legitimate version of the schema? The serial key messages are _old_ as hell and they aren't changed.

**Comment by Spoderman12** [comment]
Yes I am using a legitimate version of the schema but it says that my key is already used and I cant do something to fix that and use it for myself.
I need a new key fast for my server without I cant progress.
Thanks for answering me,
Cordially,

**Comment by Spoderman12** [comment]
I think it's because I didnt refreshed hostname in "my serials" intro cloud 16 plugins?

**Comment by ruben-16** [comment]
You don't need your serial linked to the plugins center to run it.
Take this to the support tickets and verify your serial with them.

**Comment by Spoderman12** [comment]
I did a ticket like 4 days agot and no answer.

**Comment by ruben-16** [comment]
Keep waiting.

**Comment by Spoderman12** [comment]
Still unauthorized after that...

**Comment by ZeferDC-Westwind** [comment]
I'm having a similar issue, It gives me an authorization error whenever I start up the server. The only difference is that there's no possibility of my serial having been stolen; I've been getting this error since the onset.

**Comment by VortixDev** [comment]
For those using legitimate keys, this is typically the issue of bad installation. Ensure that the **serial.cfg** contains the serial key as listed on your store product page. If it doesn't, set it as such. If you already did that but its content changed to something else upon launching the server, try renaming the **serial.cfg** to **serial.cw**. For other cases, raise the issue with store support.
