### ISSUE TITLE
"You cannot create anymore characters"

### ISSUE THREAD

**Issue by dj-34** [CloudSixteen/Clockwork#291]
Hello guys, i have a problem with characters... I cannot create characters, maybe limit?
Yes, I know that now someone will tell me to just remove these characters, but it's characters not displayed in the panel. How i can delete these characters? Please, help!!!

**Comment by 10sa** [comment]
If you are the owner of the server, whether it is to check the settings?
The number of possible characters generated maybe set to zero.

**Comment by dj-34** [comment]
No, i'm just a player

**Comment by 10sa** [comment]
Contact your admin to look good idea to check for errors in the DB.
What about the others?

**Comment by dj-34** [comment]
Truth is not such an important issue as it is now, to contact the admin I can't :C

**Comment by dj-34** [comment]
I mean the automatic deletion of characters

**Comment by 10sa** [comment]
I think it is unlikely the user'll be able to solve this problem.
You did try to retry?

p.s > Sorry, it looks a bit weird as a translator in use.

**Comment by dj-34** [comment]
I'm admin on the server, maybe I can somehow remove the character through the console or command
yeah, i know, 
Sorry for my English, I'm not from America

**Comment by dj-34** [comment]
Yeah, I was trying to say, but he doesn't listen, responding to the fact that it's hard.

**Comment by dj-34** [comment]
So I'm trying to solve the problem yourself

**Comment by dj-34** [comment]
I think I'm the only one who faced this problem

**Comment by ruben-16** [comment]
How many characters do you have? Trying clicking the red x to delete a character. If you can't solve this issue, contact the server owner to persue this issue.

**Comment by dj-34** [comment]
it's characters not displayed in the panel.

**Comment by ruben-16** [comment]
Contact a server owner/administrator or whoever you think has access to MySQL as it's a problem on their end.

**Comment by VortixDev** [comment]
I believe this limiting mechanism works by allowing you one character for each faction that you have access to, plus the number of permitted additional characters (as described by the `additional_characters` config). Note, when I say "one character for each faction", I mean that each faction you have access to contributes towards a total character count. You could, then, have all characters of one faction.

For any further issues relating to this, please have the server owner raise an issue themselves.
