### ISSUE TITLE
Schema Hook Issue

### ISSUE THREAD

**Issue by bulletowns** [CloudSixteen/Clockwork#293]
Hello there,

I appear to be having a schema hook issue, it says it is a plugin that is probably interfering with this and I need to know what is wrong with it.

I've attached the image below.
![31770438db1a8c8bbcf37bb5671a8c7f](https://cloud.githubusercontent.com/assets/3174058/16533653/3cbc6c46-3fd2-11e6-86ba-6609debcccf1.png)

**Comment by VortixDev** [comment]
This is just a warning to let you know that schema behaviour is being overridden. Depending on the plugin, this may be necessary to achieve its goal. Regardless, this is a warning rather than an error, and is ultimately caused by a plugin you've downloaded.
