### ISSUE TITLE
Cider 2 Tied hands on spawn

### ISSUE THREAD

**Issue by blasto652** [CloudSixteen/Clockwork#296]
As the title says i went and installed cider two and whenever i spawn in with a char it says "Your hands are tied" and i cant ddo anything.I already looked on the forums for a fix and the one that was posted had the file deleted or moved as its not downloadable any more.Can anyone help please?

**Comment by 8bitMafia** [comment]
#281

**Comment by blasto652** [comment]
I ended up getting the fix (Though i required to sign into my forums account to do so) but why does this problem even exist?I guess its because cyder 2 is a less populated gamemode so kuro and others dont think to update its major bugs?

**Comment by xRJx** [comment]
This issue is a duplicate of #281.
