### ISSUE TITLE
Inventory Refresh Issues

### ISSUE THREAD

**Issue by 8bitMafia** [CloudSixteen/Clockwork#297]
All of the servers with Clockwork 0.96.2 installed seem to have issues with inventory refreshing. For example you pick up an item and the inventory panel is not built and you open it the item will not be there, so you have to reopen the tab menu for it to refresh. From what I have tested if the panel is open in the tab menu prior to picking up the item it will refresh without issue. This is a big blow to fast pace manage and can mess with game play.

Video:
https://i.gyazo.com/a665aa0fc58fc273bf3a90db785bd8b7.mp4

**Comment by VortixDev** [comment]
Thanks for reporting this: it seems to be fixed by the latest release.
