### ISSUE TITLE
[Atomic] Character Creation Bug

### ISSUE THREAD

**Issue by valtorix** [CloudSixteen/Clockwork#307]
Greetings,

My comrade seems to be having an issue with the schema which so far has only been unique to him.
In character creation on the server, he cannot continue past the assignment of his SPECIAL points as the form has completely blocked the Next/Finish button.

Steps he's taken:
- Re-installation of Gmod
- Unsubscribing from all workshop items, only subscribing to the content needed for the server and re-downloading the gamemode
- Resizing his Gmod client to Windowed and back again to fullscreen

To no effect, some of the steps seem unrelated but he decided better to be safe than sorry. He's trying another attempt as I post this, i've told him to snip the problem if he can't resolve it; when he does i'll attach it here. 

Any help would be much appreciated as we're stumped to as what's causing the issue. As i've stated, everyone else including new players have no problems with the schema, he's the only one with this issue; but we've restarted the server since his problem and it still didn't seem to help; for whatever that's worth.

Thank you

**Comment by MrMe0w** [comment]
He seems to be running gmod at a really low resolution, which is the only reason SPECIAL panel will block the buton. I'd suggest your friend to get/borrow a nice 1080p monitor and try again. Plus getting said monitor will definitely improve your friend's experience with the computer (assuming he has a really small screen at the moment).
I think this will get fixed eventually, so, even if he can't get a new monitor - he could simply wait for a fix to come out.

**Comment by valtorix** [comment]
MrMe0w,

Thank you kindly for the great advice and responding! It does make sense, considering he re-installed everything it might just be his resolution. Currently he uses a laptop with a resolution of: 1280x600, as I post this he will be trying this solution come Tuesday and will let me know if he succeeds or not.

Other than a possible bug in the schema, if it's not his Screen Resolution would you know of any potential way to resolve this conflict? He sort of plays a big part on the server, would suck not to have him on it, you know? 

Thank you regardless :-)

**Comment by valtorix** [comment]
UPDATE: Please ignore my response. I HAVE GREAT NEWS! Thanks to your sound advice, the gamemode is now functioning properly for my friend; you were right the problem WAS the screen resolution. 

Thank you kindly <3

**Comment by valtorix** [comment]
UPDATE: Please ignore my response. I HAVE GREAT NEWS! Thanks to your sound advice, the gamemode is now functioning properly for my friend; you were right the problem WAS the screen resolution. 

Thank you kindly <3
