### ISSUE TITLE
Console spam error

### ISSUE THREAD

**Issue by thecoolmaster** [CloudSixteen/Clockwork#311]
When i join my gmod server i get a gray screen and my console gets spamed with
[Clockwork] The 'HUDShouldDraw' hook failed to run.
gamemodes/clockwork/framework/cl_kernel.lua:1360: attempt to call method 'HUDShouldDraw' (a nil value)

Can someone please help?

**Comment by VortixDev** [comment]
I can't replicate this, but I just put out a new release, so if you're experiencing this please give that a try.
