### ISSUE TITLE
Non-Admin versions of /rankpromote and /rankdemote do not work

### ISSUE THREAD

**Issue by TheDarkBox** [CloudSixteen/Clockwork#319]
When I use the command "/rankpromote name false" it gives me the following error:

[ERROR] gamemodes/clockwork/framework/sh_kernel.lua:3848: attempt to call method 'gsub' (a nil value)
  1. Replace - gamemodes/clockwork/framework/sh_kernel.lua:3848
   2. Decode - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:460
    3. unknown - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:1245
     4. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:160
      5. unknown - lua/includes/extensions/net.lua:32

I am using a Star Wars RP schema by duck (factions have ranks in it).

**Comment by jeanflo** [comment]
i have the same problem
