### ISSUE TITLE
Can't change gamemode to Clockwork HL2RP?

### ISSUE THREAD

**Issue by Ajaydood** [CloudSixteen/Clockwork#320]
Okay, so I bought the Clockwork schema and everything is in the right places in their files. I just need to know the name of the gamemode to change it to in the commandline so it boots into hl2rp. This is the log it gives me when I change the gamemode. I tried every name I could think of. Please help. Thanks.

Couldn't change active gamemode - 'cwhl2rp' not found

**Comment by xRJx** [comment]
The gamemode name is cwhl2rp, as you used it. Make sure your gamemode is installed and configured properly (before you say it; I know I know, late reply...).
- http://wiki.cloudsixteen.com/installation
- http://wiki.cloudsixteen.com/configuration

**Comment by Ajaydood** [comment]
Yeah. Late reply. I quit GMOD a while back unfortunately. I just don't find
interest anymore, I fixed it at the time but the server got no players, so
I cancelled my server. Thanks for the reply though!

**Comment by xRJx** [comment]
I'm glad to hear you ended up fixing it, sorry I couldn't have helped sooner.
