### ISSUE TITLE
Serious problems with clockwork

### ISSUE THREAD

**Issue by ferzux** [CloudSixteen/Clockwork#321]
Hello, I got lot of problems with clockwork.

One of this: 
 [Clockwork:Kernel]
The 'GetTargetPlayerText' clockwork hook has failed to run.
gamemodes/clockwork/gamemode/external/utf8.lua:1953: UTF-8 string terminated early

Two of this: My friend and other people (not all) can't create a character, them give a error "Limit is reached" or "Character with this name atready exists", but man hasn't any characters, but he can't create character. 

Info:
Mysql - I doesn't change any mysql settings in clockwork.cfg, it uses server
Clockwork version - the newest version (0.96.3d)
HL2RP version - the newest (1.08)
I was modifying core files (but only framework folder), I was translating it on russian.

I'm really need your help, people are leaving from my this server, because this problem are very serious.
I'm not very strong in english, so sorry if I say something wrong.

**Comment by MrMe0w** [comment]
uninstall

**Comment by VortixDev** [comment]
For those facing this issue, please retry with the latest version of Clockwork.
