### ISSUE TITLE
Plugins wont install.

### ISSUE THREAD

**Issue by arinehart911** [CloudSixteen/Clockwork#322]
I tried sending a support ticket but it wouldn't send, so I'm asking you guys for help.

So recently, we've been trying to install plugins for our HL2RP. Our server console says this:

[CloudAuthX] Checking and downloading default plugins...
[CloudAuthX] delaylooc plugin is up to date.
[CloudAuthX] storeflag plugin is up to date.
[CloudAuthX] trackstats plugin is up to date.
[CloudAuthX] reportplayer plugin is up to date.
[Plugin Center] Skipping Apply (missing a plugin.ini)
[Plugin Center] Skipping Metropolice Model Pack Animations Fix (missing a plugin.
ini)
[Plugin Center] Skipping MetroPolice Full Customization (missing a plugin.ini)
[Plugin Center] Updated a total of 0 subscribed plugin(s).

I've never done this before, so I got confused. I tried making a plugin.ini for "Apply", but that didn't work either. I'm really lost and in need of assistance. Is anyone able to help?

Thank you!

**Comment by trurascalz** [comment]
Hi,

If your still experiencing this issue please open  a ticket on the store.
