### ISSUE TITLE
Clockwork errors with atomic

### ISSUE THREAD

**Issue by BarneyfromBlackmesa** [CloudSixteen/Clockwork#323]
Every single time I join my atomic server, and click new on the characters screen, I get this error: 

 [Clockwork] The 'Tick' hook failed to run.
gamemodes/clockwork/framework/derma/cl_character.lua:273: attempt to index field 'subLabel' (a nil value)

I also sometimes get this error:

[ERROR] gamemodes/clockwork/framework/derma/cl_character.lua:266: attempt to index field 'subLabel' (a nil value)
  1. FadeOutTitle - gamemodes/clockwork/framework/derma/cl_character.lua:266
   2. OpenPanel - gamemodes/clockwork/framework/derma/cl_character.lua:304
    3. OpenNextCreationPanel - gamemodes/clockwork/framework/libraries/client/cl_character.lua:196
     4. Callback - gamemodes/cwatomic/schema/cl_theme.lua:405
      5. DoClick - gamemodes/cwatomic/schema/cl_theme.lua:372
       6. unknown - gamemodes/clockwork/framework/derma/cl_labelbutton.lua:83
Any help would be appreciated.

**Comment by SellMG** [comment]
You modified your schema?

**Comment by jacksonsp117** [comment]
Same problem here, IDK what it is. Waiting for solution. And didn't edit schema. I just installed it and I know I installed it properly.

**Comment by SellMG** [comment]
Test with 0.96.2, it's works for me.
