### ISSUE TITLE
Assertion failed: CFileWriterThread

### ISSUE THREAD

**Issue by iamgiygas** [CloudSixteen/Clockwork#325]
http://i.imgur.com/hijAcf8.png
For some reason, if anyone connects, the server crashes with "Assertion failed: CFileWriterThread:" along with where it failed.

I tried removing some plugins that I thought were causing the issue, but that didn't do much. If there was an easy way to unsubscribe from all plugins, I would, but the server seemed to be working fine yesterday, until my friend tried to join while I was on.

It seems like plugin zips are being corrupted and such. I can't figure out what's going wrong. Even Gmod addons are causing crashes, such as PAC3.

**Comment by VortixDev** [comment]
For anyone experiencing this, please update to the latest version of Clockwork and ensure that the active user has read/write/execute permissions for the server files as appropriate.
