### ISSUE TITLE
Server Error

### ISSUE THREAD

**Issue by GhostPick00** [CloudSixteen/Clockwork#326]
Hello, I'm having the problem with the 'PlayerTick' plugin. Seems to be the 'itemTable' problem... does anyone knows how to fix this problem? Thank you...

[Error]
gamemodes/clockwork/framework/libraries/sh_inventory.lua:271: attempt to call local 'itemTable' (a nil value)

**Comment by VortixDev** [comment]
I can't replicate this, but I just put out a new release, so if you're experiencing this please give that a try.
