### ISSUE TITLE
Character Wiping

### ISSUE THREAD

**Issue by Vj593** [CloudSixteen/Clockwork#328]
Every time I join the server I frequent (The Earthfall Network HL2RP). It doesn't let me access the character menu like I don't have any characters. But when I try to recreate my character, it says I already have a character of that same name. When I create a new character with a new name, it works, until I log into the server again and the process repeats itself. I haven't tried to see if the problem happens on other servers. I've been struggling to solve this for weeks now and am out of suggestions. I've tried restarting my computer, relogging the game, even reinstalling Garry's Mod. None of it seems to work, even a little.

**Comment by VortixDev** [comment]
This seems to be a server-specific issue: this is something to be raised with server management, as the current release of Clockwork doesn't exhibit this vehaviour.
