### ISSUE TITLE
Errors on loading into CW HL2 server.

### ISSUE THREAD

**Issue by BetaDesh** [CloudSixteen/Clockwork#329]
So I got my server to actually recognize the gamemode but now I'm stuck on the intro screen with no text, buttons, or anything coming up. In the in game console this showed up a few hundred times in a row:

[Clockwork] The 'HUDDrawScoreBoard' hook failed to run.
lua/includes/modules/draw.lua:71: 'hl2_IntroTextSmall' isn't a valid font

and in console.log I got [](https://pastebin.com/N5jw3pJi)

Sorry if this is a stupid issue or something. I'm relatively new to this.

**Comment by Nuclearbeat** [comment]
Having this issue too.

**Comment by VortixDev** [comment]
For those facing this issue, please retry with the latest version of Clockwork.
