### ISSUE TITLE
white screen

### ISSUE THREAD

**Issue by jasg-redwood** [CloudSixteen/Clockwork#332]
A white screen prevents me from getting to the character selection screen, I tried everything, reset my PC, Steam, re-install GMOD, re-install Steam. Nothing is working, whenever I join the server it just fades to white and there is nothing I can do from there. Please help I installed the latest update for GMOD by the way if that has anything to do with it.

**Comment by VortixDev** [comment]
For anyone experiencing this, please try updating to the latest Clockwork version.
