### ISSUE TITLE
« Illegal characters »

### ISSUE THREAD

**Issue by TheRealEnderHero** [CloudSixteen/Clockwork#336]
For a better translation, we should add the ability to add the characters said « illegal » (In reference to the gamemode DarkRP), such as : α ß Á á À à Å å Ä ä Æ æ Ç ç É é È è Ê ê Í í Ì ì Î î Ñ ñ Ó ó Ò ò Ô ô Ö ö Ø ø Ú ú Ù ù Ü ü Ž ž, « »,  etc...

Here is a list more detailed : http://www.copypastecharacter.com/all-characters

**Comment by kurozael** [comment]
Any idea on how this is achieved?

**Comment by TheRealEnderHero** [comment]
I don't know, when I was translating the HL2RP Schema in French, I have to encode some document in UTF-8 without BOM or in OEM 863: French. Maybe it could help?
