### ISSUE TITLE
Wrong language text?

### ISSUE THREAD

**Issue by 10sa** [CloudSixteen/Clockwork#339]
- sh_english.lua file 206 line.
`CW_ENGLISH["YouHaveMaxOfThis"] = "You have the maximum of this %1!"; `

 - "You have the maximun of this  **_%1_** !"
Most other formats use # rather than %. is this the valid format?

**Comment by 10sa** [comment]
* sh_english.lua file 209 line.
`CW_ENGLISH["PlayerNotCorrectGenderForFaction"] = "#1 is not the correct gender for the #1 faction!";`
 - The text specification format seems to be duplicated. (#1)

**Comment by 10sa** [comment]
* sh_english.lua file 475, 476
`CW_ENGLISH["ShowICMessagesDesc"] = "Whether or not to show you any in-character messages.";`
`CW_ENGLISH["ShowICMessagesDesc"] = "Show in-character messages.";`

* Duplicate language key value.

**Comment by 10sa** [comment]
* sh_english.lua file 485, 486
`CW_ENGLISH["ESPInterval"] = "ESP Interval";`
`CW_ENGLISH["ESPInterval"] = "The amount of time between ESP checks.";`

 * Duplicate language key value.

**Comment by kurozael** [comment]
Thanks! That's really handy I'll fix these tomorrow:)

**Comment by kurozael** [comment]
Hey @10sa, can you add me on Steam http://steamcommunity.com/id/kurozael

I'd like to introduce a Korean board on the forums which you could moderate...

**Comment by 10sa** [comment]
@kurozael 
Of course, I am glad to be able to participate in the translation.
I will add a friend.

**Comment by kurozael** [comment]
Thanks Tensa :)
