### ISSUE TITLE
Crafting is broken

### ISSUE THREAD

**Issue by TacticalToaster** [CloudSixteen/Clockwork#347]
Current GitHub and normal download versions of the crafting system are broken. Server gets the error
[Clockwork:Command]
The 'CraftBlueprint' command has failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:4112: attempt to index local 'player' (a nil value)

**Comment by waythink** [comment]
Same thing.

**Comment by xRJx** [comment]
This issue has been fixed.
