### ISSUE TITLE
When creating a male character, after selecting a model, the next button becomes unclickable.

### ISSUE THREAD

**Issue by KERNEL01** [CloudSixteen/Clockwork#370]
Clockwork, Cider Two.

Tested with and without plugins, still the same issue, if I create a female character I'm able to proceed to the game, but if I create a male character, the next button becomes unclickable after selecting a model.

No console errors in client or server to help.
![image](https://user-images.githubusercontent.com/7692725/30236870-e8cc1b58-9567-11e7-8ef4-7395aa61108b.png)

**Comment by kurozael** [comment]
That's strange it works for others, but the problem might be that you're running Cider Two and I've not tested Clockwork 0.97 with C2 yet but when I'm back from Greece in 5 days I will be updating all other schemas to be fully compatible with it.

**Comment by KERNEL01** [comment]
Take your time, I'm not in a rush, and am just using this is a method to learn Lua (I'm really new to this).

Cider Two definitely doesn't get much attention, but I think it could be really useful as an alternative to Present day roleplay. 

The reason its popular is faltering is because it doesn't really work as an out-of-the-box gamemode and requires a lot of work and content (for me, part of the charm.)

**Comment by Aberidius** [comment]
I am able to recreate this error while running on the latest CW.

**Comment by KERNEL01** [comment]
any traction with this?

**Comment by Aberidius** [comment]
Run the game in fullscreen until the issue has been fixed. The model preview is overlapping the button.

**Comment by KERNEL01** [comment]
Thanks, I'll test this soon.
