### ISSUE TITLE
Wrong language key values.

### ISSUE THREAD

**Issue by 10sa** [CloudSixteen/Clockwork#375]
sh_english.lua in 980 ~ 983.
 * CW_ENGLISH["CmdPlyVoiceBan"] = "Ban a player from the server.";
 * CW_ENGLISH["CmdPlyVoiceBanDesc"] = "<string Name|SteamID|IPAddress>";
 * CW_ENGLISH["CmdPlyVoiceUnban"] = "Ban a player from the server.";
 * CW_ENGLISH["CmdPlyVoiceUnbanDesc"] = "<string Name|SteamID|IPAddress>";

This language key value is voice ban describe, but value is not include "voice ban" describe.
This can be misleading to the user.

(and unban describe is  same ban describe, it's need fix.)

**Comment by 10sa** [comment]
sh_english.lua file 991, 993 lines.
 * CW_ENGLISH["CmdRankDemoteDesc"] = "<string Name> [boolean IsForced]";
 * CW_ENGLISH["CmdRankPromoteDesc"] = "<string Name> [boolean IsForced]";

Almost Boolean parameter name is bool, but this describe is not bool. (Inconsistent name)

**Comment by kurozael** [comment]
Thanks @10sa I'll fix these when I get home, good spot! :)

**Comment by kurozael** [comment]
All done :)
