### ISSUE TITLE
The space before the end

### ISSUE THREAD

**Issue by karl-police** [CloudSixteen/Clockwork#381]
https://github.com/CloudSixteen/Clockwork/blob/e2d35ad23dfa19e031c43915cc1773647f47ac9b/Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_english.lua#L228

This was the space before the end I was talking about.

**Comment by netxdaguy** [comment]
make a pull request then?

**Comment by 10sa** [comment]
@karl-police 
Fixed. close this issues please.

60d9135bc3b708296b3fd1b364160808b8d5e7f7

**Comment by xRJx** [comment]
The master branch is showing the correction: https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/language/sh_english.lua#L228

This is resolved now.
