### ISSUE TITLE
Some problems with cash and language.

### ISSUE THREAD

**Issue by Zerossim** [CloudSixteen/Clockwork#389]
When you don't have much money to pay to salesman.

[ERROR] gamemodes/clockwork/plugins/salesmen/plugin/sv_plugin.lua:76: calling 'FormatCash' on bad self (string expected, got table)
  1. FormatCash - [C]:-1
   2. unknown - gamemodes/clockwork/plugins/salesmen/plugin/sv_plugin.lua:76
    3. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:127
     4. unknown - lua/includes/extensions/net.lua:32
///
Appears when player trying to pick up money from ground.

[Clockwork:Kernel]
The 'EntityHandleMenuOption' Clockwork hook has failed to run.
gamemodes/clockwork/framework/libraries/sh_lang.lua:179: attempt to index a string value with bad key ('GetInfo' is not part of the string library)
///

**Comment by Member05022018** [comment]
Can confirm this still occurs. Picking up money from the ground seems impossible.

**Comment by sannysc** [comment]
This was fixed in the aforementioned commits.
