### ISSUE TITLE
Models spazzing out then turning invisible.

### ISSUE THREAD

**Issue by Roachdaripper** [CloudSixteen/Clockwork#398]
I get this spammed in my console if they have a weapon equipped, whether it's selected or not.
cw_gear[277]:SetAngles( nan nan 0.000000 ): Ignoring unreasonable angles.
cw_gear[277]:SetPos( nan nan -nan(ind) ): Ignoring unreasonable position.
cw_gear[277]:SetAngles( nan nan 0.000000 ): Ignoring unreasonable angles.
cw_gear[277]:SetPos( nan nan -nan(ind) ): Ignoring unreasonable position.

**Comment by Roachdaripper** [comment]
Bump?

**Comment by sannysc** [comment]
Post your item code.

**Comment by Roachdaripper** [comment]
It's not item-specific, the character models disappear after their heads and torsos shake wildly, having some basic modelling knowledge I assume that CW is fucking with the pose parameters for some reason.

**Comment by sannysc** [comment]
Nothing I can really do without more information. You haven't provided me any info besides the error itself, which isn't very useful on its own.
