### ISSUE TITLE
 Faction Issue

### ISSUE THREAD

**Issue by WizzyDev** [CloudSixteen/Clockwork#399]
NOT RUNNING CRACKED CW OR PIRATED I ASSURE YOU

So basically it only started recently, but the CWU faction that is using the same code as citizen wont save whitelists or characters.

**Comment by WizzyDev** [comment]
Found out why it broke, fixed it. Removed a few files by mistake

**Comment by netxdaguy** [comment]
This isn't an issue with the framework.
If you need help I'd suggest actually submitting your code and posting it in a relevant place.

**Comment by WizzyDev** [comment]
im new to this system i DO NOT know how to use it.

**Comment by xRJx** [comment]
As already mentioned by @netxdaguy, this isn't an issue with the Clockwork framework. This GitHub and the issues posted are meant to identify bugs/error with the Clockwork framework, not things that are for other schemas or custom code that's not working. You'd be better off posting your issue on CloudSixteen's Development forum section found here: http://forums.cloudsixteen.com/forums/development.18/

Be sure to include the code you're using and any errors from your server's console log.
