### ISSUE TITLE
CWU Faction No CID

### ISSUE THREAD

**Issue by WizzyDev** [CloudSixteen/Clockwork#400]
So basically the CWU faction wont give players a CID, it uses the same code as citizens just with different models etc, here my CWU faction code: 

local FACTION = Clockwork.faction:New("Civil Workers' Union");

FACTION.useFullName = true;
FACTION.whitelist = true;
FACTION.material = "halfliferp/factions/cwu";
FACTION.giveCard = "cid_card";

FACTION.models = {
	female = {
		"models/army/female_01.mdl",
		"models/army/female_02.mdl",
		"models/army/female_03.mdl",
		"models/army/female_04.mdl",
		"models/army/female_05.mdl",
		"models/army/female_06.mdl",
		"models/army/female_07.mdl"
	},
	male = {
		"models/wichacks/ted.mdl",
		"models/wichacks/vance.mdl",
		"models/wichacks/van.mdl",
		"models/wichacks/sandro.mdl",
		"models/wichacks/mike.mdl",
		"models/wichacks/joe.mdl",
		"models/wichacks/eric.mdl",
		"models/wichacks/erdim.mdl",
		"models/wichacks/art.mdl"
		
	};
};

-- Called when a player is transferred to the faction.
function FACTION:OnTransferred(player, faction, name)
	if (Schema:PlayerIsCombine(player)) then
		if (name) then
			local models = self.models[ string.lower( player:QueryCharacter("gender") ) ];
			
			if (models) then
				player:SetCharacterData("model", models[ math.random(#models) ], true);
				
				Clockwork.player:SetName(player, name, true);
			end;
		else
			return false, "You need to specify a name as the third argument!";
		end;
	end;
end;

FACTION_CWU = FACTION:Register();

**Comment by sannysc** [comment]
This is an HL2 RP problem, so I can't fix it in this repository.

**Comment by WizzyDev** [comment]
Okay, thank you. (I'm new to this support system)

**Comment by xRJx** [comment]
See https://github.com/CloudSixteen/Clockwork/issues/399#issuecomment-362657695
