### ISSUE TITLE
cl_init module not found

### ISSUE THREAD

**Issue by daxtothemaxx1** [CloudSixteen/Clockwork#402]
I've just bought a new server host I'm currently using SerenityServers. I extracted everything to my server host and it doesn't work. Here are my logs

FIND [/usr/gmodcontent/cstrike/*.vpk]
ADDING [/usr/gmodcontent/cstrike/cstrike_pak_000.vpk]
Adding Path: [/usr/gmodcontent/cstrike]
Couldn't load shader dll: game_shader_generic_garrysmod_srv.soConVarRef mat_dxlevel doesn't point to an existing ConVar
Game_srv.so loaded for "Garry's Mod"
Initializing Steam libraries for Workshop..
WS: Waiting for Steam to log us in......
WS: Fetching collection info...
Processing collection 778917816...
   Collection 'NRP HL2RP Collection'
   7 new addons
WS: Finished!
 
WS: Processing 7 addons...
Processing addon 7: Stacker STool (104479831)...
   Addon up to date, mounted!
Processing addon 6: Metropolice Pack (104491619)...
   Addon up to date, mounted!
Processing addon 5: Half-Life 2 Tools (104619813)...
   Addon up to date, mounted!
Processing addon 4: Half-Life 2 Tools Extras (105565372)...
   Addon up to date, mounted!
Processing addon 3: Clockwork: HL2 RP Content (108727894)...
   Addon up to date, mounted!
Processing addon 2: Combine APC (118997241)...
   Addon up to date, mounted!
Processing addon 1: rp_c18_v1 (132931674)...
   Addon up to date, mounted!
WS: Finished!
Unknown command "cl_cmdrate"
Unknown command "cl_updaterate"
Unknown command "rate"
'banned_ip.cfg' not present; not executing.
'banned_user.cfg' not present; not executing.
Changing gamemode to HL2 RP (cwhl2rp)
WARNING: Port 27005 was unavailable - bound to port 27008 instead
Network: IP 64.110.24.246, mode MP, dedicated Yes, ports 27055 SV / 27008 CL
Error loading cfg/trusted_keys_base.txt
Error loading cfg/pure_server_minimal.txt
PREP OK
[Clockwork] Framework is initializing...
Couldn't include file 'includes/modules/cloudauthx.lua' (File not found) (@gamemodes/clockwork/gamemode/init.lua (line 33))
 
[ERROR] gamemodes/clockwork/gamemode/init.lua:33: Module not found!
  1. require - [C]:-1
   2. unknown - gamemodes/clockwork/gamemode/init.lua:33
    3. DeriveGamemode - [C]:-1
     4. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6
 
Couldn't Load Init Script: 'clockwork/gamemode/init.lua'
[AddCSLuaFile] Couldn't find 'weapons/gmod_tool/shared.lua' (<nowhere>)
ERROR: Trying to derive entity prop_npc_crate from non existant entity base_gmodentity!
ERROR: Trying to derive entity prop_headcrabcanister from non existant entity base_gmodentity!
ERROR: Trying to derive entity prop_trigger from non existant entity base_gmodentity!
Making workshop gamemode available for client download
ConVarRef room_type doesn't point to an existing ConVar
Executing dedicated server config file server.cfg
Using map cycle file cfg/mapcycle.txt.
Nav File is wrong or something (4)
Initializing Steam libraries for secure Internet server
No account token specified; logging into anonymous game server account.  (Use sv_setsteamaccount to login to a persistent account.)
'banned_ip.cfg' not present; not executing.
'banned_user.cfg' not present; not executing.
Connection to Steam servers successful.
   Public IP is 64.110.24.246.
Assigned anonymous gameserver Steam ID [A-1:3355048965(9628)].
VAC secure mode is activated.

I tried extracting the files onto a server that I downloaded on my pc and it worked fine. Please help!

**Comment by netxdaguy** [comment]
Some of the files may not have copied over correctly. Try reinstalling Clockwork and see if that works out.

**Comment by daxtothemaxx1** [comment]
@netxdaguy I tried that but it didn't work. I'm really confused

**Comment by sannysc** [comment]
You did not install gmsv_cloudauthx_linux.dll in your garrysmod/lua/bin folder on the server.
Your host may have prevented you from placing that file, in which case, you will have to contact them.
