### ISSUE TITLE
Plugins doesn't work

### ISSUE THREAD

**Issue by XPGamingXPDK** [CloudSixteen/Clockwork#403]
**Hello guys.**

So I haven't really changed anything on HL2RP, I've checked and my Database work and the gamemode work, the problem is those plugins I have added they doesn't wanna work, they just say something(Check Below) and then it won't work.

[Clockwork:Passive Dispatch Annoucements]
The 'ClockworkSchemaLoaded' hook has failed to run.
[string "CloudAuthX"]:13: attempt to index field 'stored' (a nil value)

[Clockwork:Plugin] The NutVendors plugin has no compatibility value set!
[Clockwork:Plugin] The betterviewdata plugin has no compatibility value set!
[Clockwork:Plugin] The books plugin has no compatibility value set!
[Clockwork:Plugin] The combine_sniper_ITEM plugin has no compatibility value set!
[Clockwork:Plugin] The combine_voices plugin has no compatibility value set!
[Clockwork:Plugin] The combinecard plugin has no compatibility value set!
[Clockwork:Plugin] The cwu plugin has no compatibility value set!
[Clockwork:Plugin] The dispatchcharges plugin has no compatibility value set!
[Clockwork:Plugin] The flashlight plugin has no compatibility value set!
[Clockwork:Plugin] The forcefields plugin has no compatibility value set!
[Clockwork:Plugin] The improvedvoicecommands plugin has no compatibility value set!
[Clockwork:Plugin] The passivedispatch plugin has no compatibility value set!
[Clockwork:Plugin] The personaldispatch plugin has no compatibility value set!
[Clockwork:Plugin] The phantommpf plugin has no compatibility value set!
[Clockwork:Plugin] The radioplugin plugin has no compatibility value set!
[Clockwork:Plugin] The rappell plugin has no compatibility value set!
[Clockwork:Plugin] The stalker_faction plugin has no compatibility value set!
[Clockwork:Plugin] The unionlock plugin has no compatibility value set!
[Clockwork:Plugin] The vortflux plugin has no compatibility value set!

**Comment by minikanyas** [comment]
These are not error messages (except the first one), they're informative.

If the plugins are not loading, there's something wrong on your end and has nothing to do with Clockwork.

**Comment by sannysc** [comment]
^ Correct
