### ISSUE TITLE
Missing textures?

### ISSUE THREAD

**Issue by ajaxxxxxxx** [CloudSixteen/Clockwork#404]
I downloaded the content and everything, ingame the menu is all missing textures/checkerboard pink.

**Comment by minikanyas** [comment]
You need to download the materials and place them in your Garry's Mod folder.
You can do it through the workshop, FastDL or manually placing them.

**Comment by ajaxxxxxxx** [comment]
Fixed it, also I can't switch characters ingame. I have to always relog, what's up with that?

**Comment by xRJx** [comment]
I'll be marking this Issue as Solved seeing as the initial issue is fixed. Please open a separate Issue if you're experiencing a different problem.
