### ISSUE TITLE
Static props not working

### ISSUE THREAD

**Issue by ajaxxxxxxx** [CloudSixteen/Clockwork#405]
So I have absolutely no idea what happened, but static props do not work anymore. Also, when interacting with a container prop such as a dresser, the moment I try to open it nothing happens. I can't do anything. What's going on???

**Comment by ajaxxxxxxx** [comment]
Nothing? Dam

**Comment by MrFrostt** [comment]
Same issue here occurred two days ago.

**Comment by Roachdaripper** [comment]
This also happens to me. I get this:

[Clockwork:Command]
The 'StaticAdd' command has failed to run.
gamemodes/clockwork/plugins/staticents/plugin/commands/sh_staticadd.lua:21: bad argument #1 to 'pairs' (table expected, got nil)

[Clockwork:Storage]
The 'EntityHandleMenuOption' hook has failed to run.
gamemodes/clockwork/plugins/storage/plugin/sv_plugin.lua:190: attempt to index field 'storage' (a nil value)

**Comment by Roachdaripper** [comment]
Also nobody on the C16 store or forums seems to want to help, so that's nice.
