### ISSUE TITLE
HL2RP MPF Faction Can't get Past Final "Next" Button in Character Creation

### ISSUE THREAD

**Issue by SapphireRed** [CloudSixteen/Clockwork#406]
As the title implies, this only happens with the MPF faction. There are no Lua errors printed to the console.

Here's what happened right before the last server restart before the issue appeared:
I deleted a large number of characters from the MySQL server, after which we restarted the server and MPF couldn't be created through the character creation menu.

Things I've tried to fix the issue:
-Completely reuploading Clockwork.
-Completely reuploading HL2RP.
-Completely deleting the "characters" table on the MySQL server to allow it to start from scratch.
-Simply restarting the server.

I'm at a loss for what could be causing this issue.

**Comment by SapphireRed** [comment]
I've now tried deleting the "players" table from the MySQL server to no avail.

**Comment by sannysc** [comment]
>There are no Lua errors printed to the console.

Which console? Check both of them.

**Comment by netxdaguy** [comment]
Have you tried reinstalling your server?

**Comment by SapphireRed** [comment]
Looks like this error is being printed to the server console:
[ERROR] gamemodes/cwhl2rp/plugins/mpfullcustomization/plugin/factions/sh_mpf.lua:19: attempt to concatenate field 'i5' (a nil value)
  1. GetName - gamemodes/cwhl2rp/plugins/mpfullcustomization/plugin/factions/sh_mpf.lua:19
   2. CreateCharacterFromData - gamemodes/clockwork/framework/libraries/sh_player.lua:969
    3. unknown - gamemodes/clockwork/framework/sv_kernel.lua:4239
     4. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:114
      5. unknown - lua/includes/extensions/net.lua:32
 
Don't know why I didn't think to check this. I'll try reinstalling the plugin.

**Comment by SapphireRed** [comment]
Update: Removing the plugin worked. I'm not going to bother reinstalling it, however. Clockwork is a delicate work of art, one bandaid is enough.
