### ISSUE TITLE
(hl2rp) Init.lua issue? maybe

### ISSUE THREAD

**Issue by Camden1963** [CloudSixteen/Clockwork#408]
This is my Error:
[Clockwork] Framework is initializing...

[CloudAuthX] Loading encrypted Clockwork externals, please wait...

 

[ERROR] lua/includes/modules/cloudauthx.lua:11: attempt to index global 'CloudAuthX' (a nil value)

  1. unknown - lua/includes/modules/cloudauthx.lua:11

   2. require - [C]:-1

    3. unknown - gamemodes/clockwork/gamemode/init.lua:33

     4. DeriveGamemode - [C]:-1

      5. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6

 

 

[ERROR] gamemodes/clockwork/gamemode/init.lua:33: Module not found!

  1. require - [C]:-1

   2. unknown - gamemodes/clockwork/gamemode/init.lua:33

    3. DeriveGamemode - [C]:-1

     4. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6

 

Couldn't Load Init Script: 'clockwork/gamemode/init.lua'

Couldn't include file 'ai_translations.lua' (File not found) (@lua/includes/util.lua (line 157))

[AddCSLuaFile] Couldn't find 'ai_translations.lua' (@lua/includes/util.lua (line 160))

Couldn't include file 'sh_anim.lua' (File not found) (@lua/includes/util.lua (line 157))

[AddCSLuaFile] Couldn't find 'sh_anim.lua' (@lua/includes/util.lua (line 160))

[AddCSLuaFile] Couldn't find 'weapons/gmod_tool/shared.lua' (<nowhere>)

Couldn't include file 'ai_translations.lua' (File not found) (@lua/weapons/weapon_mad_base/init.lua (line 4))

ERROR: Trying to derive entity aw2_dropship from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_gunship from non existant entity base_gmodentity!

ERROR: Trying to derive entity sammyservers_textscreen from non existant entity base_gmodentity!

ERROR: Trying to derive entity prop_trigger from non existant entity base_gmodentity!

ERROR: Trying to derive entity prop_npc_crate from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_manhack from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_hk from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_hunterchopper from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_hunterchopper from non existant entity base_gmodentity!

ERROR: Trying to derive entity prop_headcrabcanister from non existant entity base_gmodentity!

ERROR: Trying to derive entity gw_hunter from non existant entity base_gmodentity!

ERROR: Trying to derive entity gw_strider from non existant entity base_gmodentity!

ERROR: Trying to derive entity aw2_dropship from non existant entity base_gmodentity!

Making workshop gamemode available for client download

Making workshop map available for client download

Unknown command "sk_plr_dmg_crowbar"

Unknown command "sk_npc_dmg_crowbar"

Unknown command "sk_plr_dmg_stunstick"

Unknown command "sk_npc_dmg_stunstick"

Using map cycle file cfg/mapcycle.txt.

Nav File is wrong or something (1)

Server logging enabled.

Server logging data to file logs\L0327002.log

Unknown command "sbox_allownpcs"

Unknown command "sbox_plpldamage"

Unknown command "sbox_playergod"

Unknown command "sbox_maxspawners"

Unknown command "sbox_maxturrets"

'banned_ip.cfg' not present; not executing.

Unknown command "inpc_custom_playermodel_faction"

Unknown command "inpc_force_player_faction"

Unknown command "inpc_custom_health"

Unknown command "inpc_weaponproficiency"

Unknown command "inpc_custom_health"

Client "|OWG| Camden1963" connected (98.16.208.129:27005).

Spawning textscreens...

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'ulib\cl_init.lua' (File not found) (@lua/autorun/ulib_init.lua (line 5))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\utf8.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 10))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\von.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 11))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 17))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork\framework\cl_kernel.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 18))

 

[ACD] Successful cleaning decals on the map.

[ACD] Successful cleaning decals on the map.

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\utf8.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 10))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\von.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 11))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 17))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork\framework\cl_kernel.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 18))

 

[ACD] Successful cleaning decals on the map.

[ACD] Successful cleaning decals on the map.

[Clockwork] Framework is initializing...

[CloudAuthX] Loading encrypted Clockwork externals, please wait...

 

[ERROR] lua/includes/modules/cloudauthx.lua:11: attempt to index global 'CloudAuthX' (a nil value)

  1. unknown - lua/includes/modules/cloudauthx.lua:11

   2. require - [C]:-1

    3. unknown - gamemodes/clockwork/gamemode/init.lua:33

     4. DeriveGamemode - [C]:-1

      5. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6

 

 

[ERROR] gamemodes/clockwork/gamemode/init.lua:33: Module not found!

  1. require - [C]:-1

   2. unknown - gamemodes/clockwork/gamemode/init.lua:33

    3. DeriveGamemode - [C]:-1

     4. unknown - gamemodes/cwhl2rp/gamemode/init.lua:6

 

Couldn't Load Init Script: 'clockwork/gamemode/init.lua'

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\utf8.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 10))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'external\von.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 11))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 17))

 

[|OWG| Camden1963|2|STEAM_0:0:104953811] Lua Error:

Couldn't include file 'clockwork\framework\cl_kernel.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 18))

**Comment by cameronjacob** [comment]
Firstly, uninstall ULib and ULX, they aren't compatible with Clockwork. Secondly, make sure the files that are missing are properly uploaded, then try again.
