### ISSUE TITLE
BMRP: You did not choose a playermodel, or the model you chose is invalid.

### ISSUE THREAD

**Issue by Babylon98** [CloudSixteen/Clockwork#409]
Hello, I'm a co-owner of a new BMRP server, and after several long hours of work, we had gotten our server to work. Unfortunately, when we made our character and selected their model, we are using the default BMRP player models by the way, and yes we did try other models, it all gave us the same error. I had checked the CMD but no errors that could've related to this problem had come up. Does anyone know a fix?

EDIT: Turns out that there's an error in the BMRP code, does anyone possibly have working code?

**Comment by Camden1963** [comment]
Quick tipi have been waiting for a response on mine for 2 days, no one helps here and sorry man I have nooooo idea

**Comment by Aberidius** [comment]
You're going to have to provide the code that you're currently using for the faction if you want help. We cannot guess what the code it.

If you want faster support, ask on the Discord or the official forum at: www.forums.cloudsixteen.com
