### ISSUE TITLE
Owner ID not working

### ISSUE THREAD

**Issue by DocKillzone** [CloudSixteen/Clockwork#411]
Has always been a very buggy way of setting the owner, yes the code is correct essentially everything is how it should be on my side. 

It says in the MySQL I am a superadmin also in the usergroup, when I was running sql lite to test it was adding and removing SA randomly. Running on cider 2 if that makes any difference

**Comment by DocKillzone** [comment]
Store version, my bad if it's not meant for here.

Been waiting for customer status for a year now to post on the forums

**Comment by sannysc** [comment]
You have to provide more information. What do you mean the owner ID isn't working? You can't use admin commands?
