### ISSUE TITLE
Console error when opening menu

### ISSUE THREAD

**Issue by Member05022018** [CloudSixteen/Clockwork#412]
I get this whenever I open up the TAB menu.

`[HTML] http://forums.cloudsixteen.com/js/xenforo/xenforo.js?_v=073095e7:222: Uncaught TypeError: Property 'group' of object #<error> is not a function`

**Comment by Aberidius** [comment]
This is because the community tab loads the C16 forums and that error is an error from the website.

**Comment by sannysc** [comment]
Yes, this is not an error you need to worry about.
