### ISSUE TITLE
Freezing upon pressing Tab

### ISSUE THREAD

**Issue by ChloeHill102** [CloudSixteen/Clockwork#415]
Its not my performance clearly.
I am running smoothly at 40-60 at most of the map,   Anytime I press Tab for the Inventory, Scoreboard or to even see the menu my game will freeze indefinetely   I am sure since I left it on the screen for 20 minutes and nothing happens except repeating sounds which were on the game last.
I have less than 30 addons installed and all they are is for the server this is happenning on         I have the workshop HL2RP content addon so it cant be a ui texture thing.     I am really running out of ideas.
I have tried verifying game cache and resetting my lua folder
I have reinstalled steam and Garry's Mod multiple times and it still happens and it is really halting my experience on HL2RP as a whole.

**Comment by Aberidius** [comment]
Have you tried this w/o any addons at all?

**Comment by sannysc** [comment]
Does this happen for every server you play on?
