### ISSUE TITLE
Player Menu shows "%1" for HP, tokens, etc...

### ISSUE THREAD

**Issue by Vimipz** [CloudSixteen/Clockwork#417]
![hl2rp 1](https://user-images.githubusercontent.com/40525695/41812544-3a2e8bd0-7725-11e8-9e3e-049fa01cc03a.PNG)

I've had this weird issue with my CW. 
CW 0.97 github version.

Anyone has encountered this issue before, or knows where the problem is?
Thanks!

**Comment by kurozael** [comment]
Are you using the corresponding (BETA) version of HL2RP from the Store with this?
