### ISSUE TITLE
Lack of Language Support - Command displays

### ISSUE THREAD

**Issue by minikanyas** [CloudSixteen/Clockwork#424]
- [There is no language support for the command tips & descriptions in the chatbox derma.](https://i.gyazo.com/cfd45a642ec59b4f6620364b678aa68d.png) [(Code)](https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua#L885-L924)
- [There is no language support for the command tips & descriptions in the Command directory page](https://gyazo.com/d778b522b9b96ca380f8dd06dd5d2ace.png) [(Code)](https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_command.lua#L352-L369)
- [There is no language support for the command tips & descriptions after typing them in the chat.](https://i.gyazo.com/3293d42d45c3dfc1be7792ba8b7d7e20.png) [(Code)](https://github.com/CloudSixteen/Clockwork/blob/master/Clockwork/garrysmod/gamemodes/clockwork/framework/libraries/sh_command.lua#L313)

**Comment by kurozael** [comment]
Which language? And are you definitely using the latest GitHub version _with_ the latest corresponding (BETA) version of HL2RP?

**Comment by minikanyas** [comment]
They won't show up properly in any language, And yes, I am using the latest version of Clockwork (GitHub) and the latest version of HL2RP (Store - Beta)

**Comment by kurozael** [comment]
That's wierd @minikanyas because the languages seem to show fine for me. Is it only the things you've linked there, and all other language stuff works okay? Do *any* commands work with language support? When I load it up I can see the commands showing in their correct language for me, which is strange.
