### ISSUE TITLE
BMRP Issues.

### ISSUE THREAD

**Issue by Babylon98** [CloudSixteen/Clockwork#427]
Hello, I've re-created my old BMRP server, and the Force Owner in the clockwork config file doesn't seem to work. It worked when I first started the server but now it's stopped working after a restart. I've also had an issue with /rankpromote for several people here is the Lua Error: [ERROR] gamemodes/clockwork/framework/sh_kernel.lua:3848: attempt to call method 'gsub' (a nil value)
  1. Replace - gamemodes/clockwork/framework/sh_kernel.lua:3848
   2. Decode - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:460
    3. unknown - gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:1245
     4. func - gamemodes/clockwork/framework/libraries/sh_datastream.lua:160
      5. unknown - lua/includes/extensions/net.lua:32 

Then we've also been having an issue where the cmd is being spammed with:
[Clockwork:PlayerSharedVars] Couldn't find key 'customClass' in SharedVars table. is it registered?

**Comment by Babylon98** [comment]
I'm not a great coder when it comes to these things, so, knowing the issues would help. Forgot to add that.

**Comment by zoephix** [comment]
can I suggest to add the SharedVar before using it.

**Comment by Babylon98** [comment]
Sorry, I was busy with school work, but again, how would I add a shared var?

**Comment by xRJx** [comment]
Pull request #436 solves this issue. Please open a new issue if you're still experiencing this problem on the newest Clockwork version.
