### ISSUE TITLE
Missing license on external server?

### ISSUE THREAD

**Issue by justinclift** [CloudSixteen/Clockwork#429]
Just went to look at the license, which potential contributors need to agree to.

The license doc points to an external location for the license:

http://www.binpress.com/license/view/l/4a3f7d2617a07ee0f8bb71372d16c09b

Attempting to visit that link fails, as the web server there just automatically redirects back to itself in an endless loop.  Eventually the server notices, and fails the request.

![binpress_server_failure](https://user-images.githubusercontent.com/406299/44630884-3967f600-a95c-11e8-8526-4876cf37a3e7.png)

Is it feasible to put the license in the repo instead, so failures of external things don't have a negative impact?

**Comment by justinclift** [comment]
Just as a data point, going to the "binpress.com" server itself bounces to the www version, which shows this:

![binpress_server_failure2](https://user-images.githubusercontent.com/406299/44675022-3554da80-aa27-11e8-8d94-b2ac0456ef44.png)

Checking if the domain itself has expired looks like it hasn't:

```
   Domain Name: BINPRESS.COM
   Registry Domain ID: 1608741933_DOMAIN_COM-VRSN
   Registrar WHOIS Server: whois.namecheap.com
   Registrar URL: http://www.namecheap.com
   Updated Date: 2018-07-30T07:28:55Z
   Creation Date: 2010-07-29T11:29:35Z
   Registry Expiry Date: 2019-07-29T11:29:35Z
   Registrar: NameCheap Inc.
   Registrar IANA ID: 1068
   Registrar Abuse Contact Email: abuse@namecheap.com
   Registrar Abuse Contact Phone: +1.6613102107
   Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited
   Name Server: DNS101.REGISTRAR-SERVERS.COM
   Name Server: DNS102.REGISTRAR-SERVERS.COM
   DNSSEC: unsigned
   URL of the ICANN Whois Inaccuracy Complaint Form: https://www.icann.org/wicf/
>>> Last update of whois database: 2018-08-27T17:27:18Z
```

Maybe the CC of whoever namecheap is billing has expired or something and no-one's noticed?

**Comment by kurozael** [comment]
I will try to do this as soon as possible but I need to find the exact license again.

**Comment by justinclift** [comment]
ping?

**Comment by trurascalz** [comment]
This license is available here: 

https://web.archive.org/web/20171125173625/www.binpress.com/license/view/l/4a3f7d2617a07ee0f8bb71372d16c09b

**Comment by xRJx** [comment]
> Oh wow. That license is horribly non-OSS.
> 
> Thanks for digging it up @trurascalz.

Yep. If my memory serves me correct; Clockwork was originally marketed as being open source but Facepunch was quick to reply by saying it wasn't, this was when Clockwork was posted on Facepunch's forums.

Regardless, I'm glad some form of the license is available, thanks for finding that @trurascalz. :)

**Comment by kiobu** [comment]
Clockwork and all of its schemas are now licensed under the MIT license.

See #540.
