### ISSUE TITLE
The 'Tick' hook failed to run.

### ISSUE THREAD

**Issue by Raiden223** [CloudSixteen/Clockwork#431]
[Clockwork:Kernel]
The 'Tick' hook failed to run.
gamemodes/clockwork/framework/sh_kernel.lua:1319: attempt to perform arithmetic on a nil value

Everytime I start up the server this happens, has anyone got a fix for this? If I try to join the server it will just spam this in the console.

**Comment by Raiden223** [comment]
Hey, sorry for the slow reply, been a bit busy.

I am using the latest version of clockwork, for some reason it does this when I link up the MySQL data with my database, I have no idea why but I hope this sheds a little light, any more info just ask and I'll try to retrieve it.

**Comment by VortixDev** [comment]
Try downloading the latest version from this repository, instead of from the store, and using that.
