### ISSUE TITLE
Phasefour on Clockwork keep launching in Base gamemode.

### ISSUE THREAD

**Issue by Contamination** [CloudSixteen/Clockwork#433]
I'm running my gamemode on wampserver to modify it directly on localhost, already did it a great amount of times so i know how it works.

So here's two errors that i found in the console.

> Couldn't include file 'external\utf8.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 10))
> 
> Couldn't include file 'external\von.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line))

If you ask, yes, i erased every old files that where in the concerned directories (such as the Lua/autorun or Lua/includes files)

Any help would be great, i don't want to be disapointed by my recent acquisition of the famous Phasefour schema!

HAve a nice day everyone!

**Comment by xRJx** [comment]
Unfortunately Phase Four is broken at the moment and requires a lot of bug fixing. I'm not sure when it would be fixed.

**Comment by VortixDev** [comment]
If you navigate to gamemodes/clockwork/gamemode/external, do you see utf8.lua and von.lua?

**Comment by minikanyas** [comment]
There must be something wrong on your end since every schema manages to boot up. 
Anyways, could you send your console log?
That would help us to find the issue.

**Comment by Contamination** [comment]
The first alarming thing is that one

> [Clockwork] Framework is initializing...
> Please wait while Clockwork initializes...
> Couldn't include file 'includes\modules\fileio.lua' (File not found) (@lua/includes/modules/cloudauthx.lua (line 5))
> 
> [ERROR] lua/includes/modules/cloudauthx.lua:5: Module not found!
>   1. require - [C]:-1
>    2. unknown - lua/includes/modules/cloudauthx.lua:5
>     3. require - [C]:-1
>      4. unknown - gamemodes/clockwork/gamemode/init.lua:33
>       5. DeriveGamemode - [C]:-1
>        6. unknown - gamemodes/cwphasefour/gamemode/init.lua:6
> 
> 
> [ERROR] gamemodes/clockwork/gamemode/init.lua:33: Module not found!
>   1. require - [C]:-1
>    2. unknown - gamemodes/clockwork/gamemode/init.lua:33
>     3. DeriveGamemode - [C]:-1
>      4. unknown - gamemodes/cwphasefour/gamemode/init.lua:6
> 
> Couldn't Load Init Script: 'clockwork/gamemode/init.lua'
> Default clips will be not be modified

and here's the second one, wich is a little after


> [[ExtReM] Contamination Breaker|2|STEAM_0:1:17598139] Lua Error:
> Couldn't include file 'external\utf8.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 10))
> 
> [[ExtReM] Contamination Breaker|2|STEAM_0:1:17598139] Lua Error:
> Couldn't include file 'external\von.lua' (File not found) (@gamemodes/clockwork/gamemode/cl_init.lua (line 11))

**Comment by VortixDev** [comment]
From what I can tell, you are using the version of Clockwork linked to on the store downloads page, correct?

If so, try downloading the version from this GitHub repo and replacing your binaries in lua/bin/ with those in the download.

**Comment by Contamination** [comment]
I'll do, thanks !

**Comment by Contamination** [comment]
Alright, it keeps running on Base gamemode, with the same errors in the console.

**Comment by sannysc** [comment]
Paste the contents of `lua/includes/modules/cloudauthx.lua` here.

**Comment by Contamination** [comment]
Thanks to @sannysc , I could identify a path through  my problem, wich was the presence of cloudauth.lua, i removed it and now i'm free again!
Thanks Sanny!
