### ISSUE TITLE
file.Read on map.bsp causes errors.

### ISSUE THREAD

**Issue by Nak2** [CloudSixteen/Clockwork#435]
I've fixed future versions by localizing the file.Read and file.Write .. but you might want to fix it.
file.Read causes errors when reading the map-file.

[StormFox - Environment mod [BETA]] gamemodes/clockwork/gamemode/external/utf8.lua:2020: attempt to perform arithmetic on local 'l' (a boolean value)
1. utf8sub - gamemodes/clockwork/gamemode/external/utf8.lua:2020
2. Read - gamemodes/clockwork/framework/sv_kernel.lua:94
3. GenerateMapdata - lua/stormfox/framework/sv_map_texture.lua:239
4. unknown - lua/stormfox/framework/sv_map_texture.lua:306

**Comment by murray-elijah** [comment]
The `|` character is not present in either character table for converting between cases in utf8.lua, so utf8sub returns that error. I'm not sure if it's in the StormFox code but lua reserves the `|` character as an OR operator, and if I'm thinking right there's a local variable somewhere with the name `|`. If this is your code, try renaming the variable to something else.

**Comment by murray-elijah** [comment]
Deleted my previous comment, as it was hilariously incorrect.

The local variable `l` in lua/stormfox/framework/sv_map_texture.lua is a boolean, and you can't perform arithmetic operations on booleans. Possibly a side effect of your localizing of file.Read and file.Write. As for a fix, I can't really help unless I have the code for StormFox (which I don't).

**Comment by murray-elijah** [comment]
Just realised I probably shouldn't edit the entire utf8 library. Check that your code in lua/stormfox/framework/sv_map_texture doesn't try to use utf8sub with any arguments that are negative @Nak2

**Comment by Nak2** [comment]
StormFox uses file.Read to scan the mapfile. So I can't really control what variables utf8sub get.
Its not an issue for SF anymore as I've localized file.Read.

But you might not want to override a function unless its absolute necessary.

**Comment by VortixDev** [comment]
The presence of non-UTF8 data in the BSP file causes this: it is not strictly an issue with either the UTF8 external library nor the GMod module (though more verbosity from the library would be good). It should be fixed in my recent pull request.

**Comment by sannysc** [comment]
Should be fixed in @VortixDev's #442.
