### ISSUE TITLE
Need a new Serial Key.

### ISSUE THREAD

**Issue by HBrpSalmon** [CloudSixteen/Clockwork#441]
I have a Clockwork HL2rp server, but it keeps saying I am not authorized to use this gamemode. People say it is because of my Serial Key being old. So I am asking if I could get a new Serial sent to my email. The reason I am posting here is because for some reason I can't login to my account for the Ticket.
Email: jessecayer636@gmail.com

**Comment by Aberidius** [comment]
We do not sent serial keys over email. You must make a ticket on the store. If you cannot log in, contact a staff member on Discord.

**Comment by xRJx** [comment]
Unfortunately this isn't the place to be posting this issue. Things posted here are pertaining to the framework and its functionality (code-wise). You'll have to get in contact with support staff on the discord/store page (as Aberidius mentioned) or on C16's forums. Best of luck, I hope you get your issue resolved.

C16 Store: http://store.cloudsixteen.com/
C16 Forums: http://forums.cloudsixteen.com/
C16 Discord (invite link): https://discordapp.com/invite/KPMu2h
