### ISSUE TITLE
I can't check how many tokens I have!

### ISSUE THREAD

**Issue by toda7057** [CloudSixteen/Clockwork#445]
I can't check how many tokens I have!
Look this
![20190101044442_1](https://user-images.githubusercontent.com/46286525/50566795-dca0a000-0d80-11e9-829d-05a4e2aec2d9.jpg)
돈 : Tokens
How can I fix it?

**Comment by xRJx** [comment]
Are you using the Korean language? If yes then please update Clockwork. This issue was previously fixed with pull request #438
