### ISSUE TITLE
Container passwords

### ISSUE THREAD

**Issue by supermicronde3** [CloudSixteen/Clockwork#478]
Hi,

A lot of my players tell me that the containers are bugged when they try to open it with a password but in fact everytime the problem is that they make mistakes with capital letters. Could you remove case sensitivity for container passwords so the gamemode would be more ergonomic ? (if it doesn't decrease password security ofc)

Thanks for anwsering me

**Comment by murray-elijah** [comment]
I just.. why? If you wanted you could do this yourself, but it's really not an issue. It's not the fault of developers that people can't remember their passwords.

**Comment by JakeDaBoss** [comment]
Pen > paper > write > ??? > Issue fixed.

**Comment by sanny-io** [comment]
> I just.. why? If you wanted you could do this yourself, but it's really not an issue. It's not the fault of developers that people can't remember their passwords.

Clearly it is an issue for him, and his issue isn't that players can't remember passwords, but that players aren't aware they are case sensitive to begin with. And for this I would ask if we really need passwords to be case sensitive. They're containers of items in a roleplaying gamemode, not secure servers holding sensitive information

I don't think it's a big deal if they were to changed to be case insensitive.

**Comment by supermicronde3** [comment]
Yeah its what i wanted to say

**Comment by moschetto** [comment]
I feel it would be most acceptable if we added a config option to test for case sensitivity.

**Comment by moschetto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add a config option to test for container password case sensitivity](https://trello.com/c/WbU0XPJx/18-add-a-config-option-to-test-for-container-password-case-sensitivity)

**Comment by supermicronde3** [comment]
Ok thanks a lot

**Comment by sanny-io** [comment]
I think then there would also be a need to inform players trying to unlock containers that they are case sensitive. It would be confusing for players accessing their containers without case sensitivity suddenly having their passwords fail to go through if the admins enable case sensitivity afterwards.

**Comment by moschetto** [comment]
> I think then there would also be a need to inform players trying to unlock containers that they are case sensitive. It would be confusing for players accessing their containers without case sensitivity suddenly having their passwords fail to go through if the admins enable case sensitivity afterwards.

That's a good point. Personally I'd rather leave it up to the server owner for them to have that option if they like it, however I do also see the point where nobody would really care if it was case-sensitive or not, since it's just containers and not a super secure thing. I'll update the note on the Trello for both cases.
