### ISSUE TITLE
All Contributors Bot Commands

### ISSUE THREAD

**Issue by kurozael** [CloudSixteen/Clockwork#479]

**Comment by kurozael** [comment]
@all-contributors please add @VortixDev  for code, maintenance, and design

**Comment by kurozael** [comment]
@all-contributors please add @kurozael for code, maintenance, design, doc, infra, plugin, security, management and ideas

**Comment by kurozael** [comment]
@all-contributors please add @sanny-io for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @trurascalz  for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @ametrocavich for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @Gr4Ss for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @xRJx for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @Skiastra for maintenance and code

**Comment by kurozael** [comment]
@all-contributors please add @alexgrist for code

**Comment by kurozael** [comment]
@all-contributors please add @impulsh for code

**Comment by kurozael** [comment]
Let's try that again but this time where I understand how the bot works.

**Comment by kurozael** [comment]
@all-contributors please add @ametrocavich for code

**Comment by kurozael** [comment]
@all-contributors please add @Gr4Ss for code

**Comment by kurozael** [comment]
@all-contributors please add @xRJx for code

**Comment by kurozael** [comment]
@all-contributors please add @Skiastra for code

**Comment by kurozael** [comment]
@all-contributors please add @alexgrist for code

**Comment by kurozael** [comment]
@all-contributors please add @impulsh for code

**Comment by kurozael** [comment]
@all-contributors please add @minikanyas for translations

**Comment by kurozael** [comment]
@all-contributors please add @10sa for translations

**Comment by kurozael** [comment]
@all-contributors please add @karl-police for translations

**Comment by kurozael** [comment]
@all-contributors please add @TheRealEnderHero for translations

**Comment by kiobu** [comment]
@all-contributors please add @kiobu for code and maintenance

**Comment by karl-police** [comment]
closed 3 days ago 🤔
