### ISSUE TITLE
Clockwork.config:Get() doesn't properly work when checking configs added by plugins

### ISSUE THREAD

**Issue by karl-police** [CloudSixteen/Clockwork#515]
I've tried to use Clockwork.config:Get("enable_third_person"):GetBoolean() in a shared file, but it doesn't work. For the client it returns false.

Using sv_allowcslua 1 to debug I found out that something else, such as cash_enabled, the client is able to get that, but the other things not.

It is able to get enable_crosshair too but yeah, apperantly any config value added by plugins, not.

This issue happens if using a plugin that doesn't add that config value. Hasn't been tested within the same plugin.

**Comment by VortixDev** [comment]
The third non-self parameter of `Clockwork.config.Add` serverside is a boolean which indicates whether the value of the given config should be shared to the client. `enable_third_person` does not set this, whereas `cash_enabled` and `enable_crosshair` both do.
