### ISSUE TITLE
There is an error connecting to the server. Do you know how to solve it?

### ISSUE THREAD

**Issue by bao1117** [CloudSixteen/Clockwork#541]
[Clockwork:Display Typing]
The 'PostDrawTranslucentRenderables' hook has failed to run.
gamemodes/clockwork/plugins/displaytyping/plugin/cl_hooks.lua:51: attempt to compare n

I was connecting to the server and it was loading. The red count came up, so I opened the console window. Is there a solution to this problem?

**Comment by kiobu** [comment]
This is probably not a bug within Clockwork. You should bring your issue to the [Discord](https://discord.gg/EEg47Dw) server for support.
