### ISSUE TITLE
cl.chatbox Issue with LOOC on Characters That Have Voice Commands Enabled.

### ISSUE THREAD

**Issue by HollerHavoc** [CloudSixteen/Clockwork#555]
Hello,

I found out that if characters have voice commands enabled, using the LOOC prefix "[[" causes this error to appear in the console:

[Clockwork:Kernel]
The 'HUDPaintForeground' Clockwork hook has failed to run.
gamemodes/clockwork/framework/libraries/client/cl_chatbox.lua:259: malformed pattern (missing ']')

The other prefix ".//" does not cause said issue.

Strangely enough if you change the prefix from "[[" to be something else it still gives that error when typing "[[" regardless of whether "[[" is actually triggering LOOC or not.

**Comment by kiobu** [comment]
Most likely a character encoding issue. Regardless, Clockwork and CW-related schemas have reached their EOL, and are no longer supported or under development. We will not attempt to fix or investigate bugs on our own accord. However, if you or another contributor want to investigate the issue and make a pull request, I will be happy to merge it.
