### ISSUE TITLE
DO NOT DOWNLOAD THIS VERSION! Grab the homonovus fork!

### ISSUE THREAD

**Issue by geemayn** [CloudSixteen/Clockwork#556]
you're not going to find out otherwise because the cloudsixteen community is full of very unhelpful and lead-brained manchildren

god help you if you have to use this piece of shit any more than you need to

**Comment by kurozael** [comment]
Are you okay hunny x

**Comment by kiobu** [comment]
I'm not able to replicate this issue. Would you mind providing an MWE to test with so we can track down the root of this bug? Thanks.
