### ISSUE TITLE
lmao kurozael you fuckin loser

### ISSUE THREAD

**Issue by geemayn** [CloudSixteen/Clockwork#557]
jesus christ man i hope you're impressing your friends. they're pretty awesome. i sure am a whiny crybaby lmao thanks for proving my point

i had to spend hours trying to figure out how to set up this shit because you decide to close off any info on this piece of crap. other people constantly have to clean up your messes because you're just plain incompetent

honestly man im real glad grist one-upped you with helix. its so great seeing him succeed way more than you ever did and you still get all pissy about it to this day

enjoy making your rts itll be just a big a mess as cloudsixteen

cant wait to be copypastad among ur friends! fuckin tools lol

**Comment by kurozael** [comment]
Are you okay hunny x

**Comment by geemayn** [comment]
are you?

**Comment by kiobu** [comment]
Thanks for the issue.
