### ISSUE TITLE
(HL2RP) Lua Errors Spamming Console

### ISSUE THREAD

**Issue by Wafflepiezz** [CloudSixteen/Clockwork#67]
Original thread: http://forums.cloudsixteen.com/index.php?topic=3396.0

"Hello, my friend is having an issue with his server regarding lua errors. Whenever we join the server, we immediately get spammed in the console by this:

http://cloud-2.steampowered.com/ugc/633044342306146222/0B1B1E3AD47AB8A2EC60934998664594F79FE321/

*gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
[Clockwork] The 'RenderScreenspaceEffects' schema hook has failed to run.
gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
[Clockwork] The 'Tick' schema hook has failed to run.
gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
[Clockwork] The 'RenderScreenspaceEffects' schema hook has failed to run.
gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
[Clockwork] The 'Tick' schema hook has failed to run.
gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
[Clockwork] The 'RenderScreenspaceEffects' schema hook has failed to run.
gamemodes/cwhl2rp/schema/cl_schema.lua:192: attempt to call method 'IsCombineFaction' (a nil value)
*

_Repeat error spam_

"
We have both looked for possible solutions such as re-installing Clockwork from the store and checking to see what is wrong with the server, but we can't find any possible solutions to fix this. His clockwork is updated to the most recent update. Any help is appreciated."

Also, I am only posting this here because my friends and I are apparently not the only ones who are experiencing this issue.

**Comment by guidigame** [comment]
Finally i can earn "Bad Coder" easilly
